### PR TITLE
fix(test-utils): do not hide Vitest output

### LINKED ISSUE #9434: Display Vitest output when running `nuxi test`
Note: you need to run `pnpm build` in order to run the test command in the framework repo

Example with `pnpm nuxi test examples/advanced/testing`:

Also, it would be nice to show at the beginning something like:

```bash
ℹ Building Nuxt project...
// ...
ℹ Starting Nuxt server...
Listening http://[::]:64405
ℹ Running tests...
// Vitest output
```

@antfu could you be up to take this task?

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

close #9434

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

`kit.logger.level` was overriding globally to hide all output including Vitest

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks!

Would it be possible also to add the others logs like mentioned in the issue?
CleanShot 2022-12-01 at 00 40 02@2x

File: packages/test-utils/src/runtime/global-setup.ts [hunk 1]
```diff
@@ -1,10 +1,17 @@
...
 
-const hooks = createTest(JSON.parse(process.env.NUXT_TEST_OPTIONS || '{}'))
+// @ts-ignore type cast
+const kit: typeof _kit = _kit.default || _kit
+
+const options = JSON.parse(process.env.NUXT_TEST_OPTIONS || '{}')
+const hooks = createTest(options)
 
 export const setup = async () => {
+  kit.logger.info('Building Nuxt app...')
```
Comment (pi0) [inline packages/test-utils/src/runtime/global-setup.ts:11]: We might to refactor this later into setup for fine gained control when to show message (build is not always happening / can include more context details in log)

**Review by pi0 — APPROVED** [review]
LGTM. Thanks 💯
