### PR TITLE
fix(nitro): pass sourcemap option through to rollup plugins

### LINKED ISSUE #2377: Rollup build chugs memory when site has a lot of components
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.15.5`
- Nuxt Version:     `2.16.0-27277936.ab1c6cb4`
- Package Manager:  `yarn@1.22.10`
- Bundler:          `Webpack`
- User Config:      `target`, `vue`, `env`, `head`, `css`, `plugins`, `storybook`, `tailwindcss`, `components`, `bridge`, `nitro`, `buildModules`, `modules`, `gtm`, `image`, `markdownit`, `screen`, `axios`, `i18n`, `googleFonts`, `build`, `alias`, `serverMiddleware`, `generate`, `router`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`, `@nuxtjs/markdownit@2.0.0`, `nuxt-svg-loader@1.2.0`, `@nuxtjs/i18n@7.2.0`, `vue-screen/nuxt`, `portal-vue/nuxt`, `nuxt-route-meta@2.3.2`, `@nuxtjs/gtm@2.4.0`, `vue-social-sharing/nuxt`
- Build Modules:    `@nuxtjs/dotenv@1.4.1`, `@nuxtjs/eslint-module@3.0.2`, `@nuxtjs/google-fonts@1.3.0`, `@nuxtjs/tailwindcss@4.2.1`, `@nuxt/image@0.6.0`, `@pinia/nuxt@0.1.5`, `~/modules/menu`, `~/modules/hubspot-properties`, `~/modules/write-redirects`, `~/modules/write-robots`, `@nuxt/bridge@3.0.0-27296160.7a78bce`
------------------------------

### Reproduction

--- Hard to reproduce, will try later

### Describe the bug

When building with `yarn nuxi generate` a website with lots of components, rollup chugs a lot of memory and trying to make it work inside e.g. a netlify build becomes impossible, even after using the whole 6gb available in the build container. 

### Additional context

_No response_

### Logs

`process.memoryUsage()` logs that I manually added in `@nuxt/nitro/dist/index.mjs`:

Before `await rollup.rollup` (in function `_build`):
```
 193.92 MB                                                                                                                  11:20:02
heapTotal 114.31 MB                                                                                                            11:20:02
heapUsed 74.3 MB                                                                                                               11:20:02
external 8.44 MB                                                                                                               11:20:02
arrayBuffers 0.1 MB   
```

after `rollup.rollup`:
```
rss 578.88 MB                                                                                                                  11:20:10
heapTotal 1633.33 MB                                                                                                           11:20:10
heapUsed 1574.61 MB                                                                                                            11:20:10
external 8.34 MB                                                                                                               11:20:10
arrayBuffers 5.58 MB 
```

after writing server bundle:
```
rss 1255.7 MB                                                                                                                  11:20:14
heapTotal 3055.27 MB                                                                                                           11:20:14
heapUsed 2972.06 MB                                                                                                            11:20:14
external 18.26 MB                                                                                                              11:20:14
arrayBuffers 15.51 MB
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #2377
see also https://github.com/rollup/plugins/issues/1064

Co-authored-by: Matteo Rigoni <matteo.rigoni@atoms.studio>

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Generating sourcemap is what seems to be causing the memory spike, and this change respects the existing `sourceMap` nitro option.

All credit to some great detective work from @Rigo-m.

On a large project this change shaved off 60% of ram usage and made the build 40% faster.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nitro/src/rollup/config.ts [hunk 1]
```diff
@@ -306,7 +307,11 @@ export const getRollupConfig = (nitroContext: NitroContext) => {
   rollupConfig.plugins.push(json())
 
   // https://github.com/rollup/plugins/tree/master/packages/inject
-  rollupConfig.plugins.push(inject(env.inject))
+  rollupConfig.plugins.push(inject({
+    // @ts-ignore
```
Comment (danielroe) [inline packages/nitro/src/rollup/config.ts:311]:
```suggestion
    // TODO: https://github.com/rollup/plugins/pull/1066
    // @ts-ignore
```

**Review by pi0 — APPROVED** [review]
Losing source-map is not ideal for development DX but let's have it as a workaround until we need to start consuming it

**Comment by danielroe** [comment]
@pi0 Source map is enabled for development:

https://github.com/nuxt/framework/blob/8d6b97a4ac8d74ede1ce135215b791126b3e9c90/packages/nitro/src/presets/dev.ts#L12

**Comment by Rigo-m** [comment]
There are some edge cases when you need the sourcemap in production to debug some stuff, although generally I think having it opt-in is better for performance reasons
