### PR TITLE
fix(bridge): transpile `@nuxt/bridge-edge`

### LINKED ISSUE #3221: nuxi dev in vite mode not working with shamefully hoisted pnpm
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `pnpm@6.30.1`
- Bundler:          `Webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27409835.c53c736`

### Reproduction

Empty project with:

`package.json`:

```json
{
  "dependencies": {
    "nuxt-edge": "^2.16.0-27358576.777a4b7f"
  },
  "devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27409835.c53c736"
  }
}
```

`.npmrc`:

```ini
shamefully-hoist = true
```

`nuxt.config.ts`:

```ts
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  bridge: {
    vite: true,
  },
})
```

Run:

```
pnpm i
pnpx nuxi dev
```

### Describe the bug

In an empty project with the latest Nuxt Bridge in vite mode, populated with shamefully hoisted pnpm, `nuxi dev` crashes because it can't load `vue2`:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vue2' imported from /Users/semenov/tmp/n/node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27409835.c53c736/node_modules/@nuxt/bridge-edge/dist/runtime/vue2-bridge.mjs
```

**`nuxi build` and `nuxi start` work fine! It's only `nuxi dev` that doesn't work.**

I totally understand that full blown pnpm support is not there. However, I believe it shouldn't at least fail in shamefully hoist (flat node_modules) mode. And it doesn't when building the production release - but crashes in dev mode.

### Additional context

Out of curiosity, I edited the 'failing' file at /Users/semenov/tmp/n/node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27409835.c53c736/node_modules/@nuxt/bridge-edge/dist/runtime/vue2-bridge.mjs:

```diff
- import Vue from 'vue2'
+ import Vue from 'vue'
```

the error changed to:

```
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#app" is not defined in package /Users/semenov/tmp/n/node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27409835.c53c736/node_modules/@nuxt/bridge-edge/package.json imported from /Users/semenov/tmp/n/node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27409835.c53c736/node_modules/@nuxt/bridge-edge/dist/runtime/asyncData.mjs
```

so it has something to do with module resolution in dev mode.

### Logs

```shell
Nuxt CLI v3.0.0-27409835.c53c736                                                                                                                                                                                 17:42:54
                                                                                                                                                                                                                 17:42:54
  > Local:    http://localhost:3000/ 
  > Network:  http://10.0.0.50:3000/

🧪  Vite mode is experimental and some nuxt modules might be incompatible                                                                                                                                        17:42:55
    If found a bug, please report via https://github.com/nuxt/vite/issues with a minimal reproduction.
ℹ Preparing project for development                                                                                                                                                                              17:42:55
ℹ Initial build may take a while                                                                                                                                                                                 17:42:55

 WARN  No pages directory found in /Users/semenov/tmp/n. Using the default built-in page.                                                                                                                        17:42:55

✔ Builder initialized                                                                                                                                                                                            17:42:55
✔ Nuxt files generated                                                                                                                                                                                           17:42:56
ℹ Vite warmed up in 14ms                                                                                                                                                                                         17:42:56
ℹ Server built in 447ms                                                                                                                                                                                          17:42:56
ℹ Waiting for file changes                                                                                                                                                                                       17:42:56
✔ Nitro built in 85 ms                                                                                                                                                                                           17:42:57
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vue2' imported from /Users/semenov/tmp/n/node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27409835.c53c736/node_modules/@nuxt/bridge-edge/dist/runtime/vue2-bridge.mjs
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:884:9)
    at moduleResolve (node:internal/modules/esm/resolve:929:18)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
[vite dev] Error loading external "/Users/semenov/tmp/n/node_modules/.pnpm/@nuxt+bridge-edge@3.0.0-27409835.c53c736/node_modules/@nuxt/bridge-edge/dist/runtime/vue2-bridge.mjs".
  at file://./.nuxt/dist/server/server.mjs:2637:353  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:10916:3)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves  #3221

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Having looked at this, #3221 is not actually a shortcoming in `externality`. It's more that `@nuxt/bridge` (which is what we add to the transpile array) is a stub that re-exports `@nuxt/bridge-edge`. pnpm doesn't nest this under `@nuxt/bridge` so there's nothing to match against.

So this PR isn't a workaround as such, but probably the correct solution.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by danielroe** [comment]
Note: will move this to transpile array rather than vite implementation.

File: packages/bridge/src/vite/server.ts [hunk 1]
```diff
@@ -50,6 +50,7 @@ export async function buildServer (ctx: ViteBuildContext) {
         /\.(es|esm|esm-browser|esm-bundler).js$/,
         '#app',
         /@nuxt\/nitro\/(dist|src)/,
+        '@nuxt/bridge-edge',
```
Comment (pi0) [inline packages/bridge/src/vite/server.ts:53]: Does it make sense to directly have `bridge-edge` in `transpile` array same as main module?

Comment (pi0) [reply packages/bridge/src/vite/server.ts:53]: never mind saw your comment now ;)

File: packages/nuxt3/src/core/modules.ts [hunk 2]
```diff
@@ -4,6 +4,7 @@ export const addModuleTranspiles = () => {
   const nuxt = useNuxt()
 
   const modules = [
+    '@nuxt/bridge-edge',
```
Comment (pi0) [inline packages/nuxt3/src/core/modules.ts:7]: neat: we canm accept an optional array for setupTranspile and add bridge from bridge usage only.

Comment (danielroe) [reply packages/nuxt3/src/core/modules.ts:7]: Do you mean we should always add `@nuxt/bridge` and `@nuxt/bridge-edge` but optionally transpile other modules when addModuleTranspiles is enabled?

Comment (pi0) [reply packages/nuxt3/src/core/modules.ts:7]: We are adding `@nuxt/bridge-edge` to the nuxt 3 sourcecode for sake of bridge support. This can be moved back to bridge.

Comment (danielroe) [reply packages/nuxt3/src/core/modules.ts:7]: Oops, missed that this was imported from nuxt3! 🤦 Yes, indeed.

File: packages/nuxt3/src/core/modules.ts [hunk 3]
```diff
@@ -1,9 +1,14 @@
 import { useNuxt } from '@nuxt/kit'
 
-export const addModuleTranspiles = () => {
+interface AddModuleTranspilesOptions {
```
Comment (pi0) [inline packages/nuxt3/src/core/modules.ts:3]:
```suggestion
export interface AddModuleTranspilesOptions {
```

**Review by pi0 — APPROVED** [review]
