### PR TITLE
fix(schema): support inline module options

### LINKED ISSUE #2630: modules with inline options not accepted in types for `modules` and `buildModules`
I updated @nuxt/bridge to npm:@nuxt/bridge-edge@3.0.0-27356801.e9128f3.

The version I used before the update was: npm:@nuxt/bridge-edge@3.0.0-27307420.6a25d3e.

And now, I have those errors. I know those modules aren't normally compatible with nuxt3 and nuxt bridge but it worked fine until now.

image

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves  #2630

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This updates modules/buildModules type to allow inline options

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/config/_common.ts [hunk 1]
```diff
@@ -225,7 +225,7 @@ export default {
    *   function () {}
    * ]
    * ```
-   * @type {(typeof import('../src/types/module').NuxtModule | string)[]}
+   * @type {(typeof import('../src/types/module').NuxtModule | string | [string, Record<string, any>])[]}
```
Comment (pi0) [inline packages/schema/src/config/_common.ts:228]: The first arg can be either string or module function:
- https://github.com/nuxt/framework/blob/main/packages/kit/src/module/install.ts#L8
https://github.com/nuxt/framework/blob/3b72b318e2c6786fa827889c02fece3247071f80/packages/nuxt3/src/core/nuxt.ts#L75

File: packages/schema/src/config/_common.ts [hunk 2]
```diff
@@ -262,7 +262,7 @@ export default {
    * decreases the size of `node_modules` in production deployments. Please refer to each
    * module's documentation to see if it is recommended to use `modules` or `buildModules`.
    *
-   * @type {(typeof import('../src/types/module').NuxtModule | string)[]}
+   * @type {(typeof import('../src/types/module').NuxtModule | string | [string, Record<string, any>])[]}
```
Comment (pi0) [inline packages/schema/src/config/_common.ts:265]:
```suggestion
   * @type {(typeof import('../src/types/module').NuxtModule | string | [typeof import('../src/types/module').NuxtModule | string, Record<string, any>])[]}
```
