### PR TITLE
fix(bridge): don't call nuxt app if instance is inaccessible

### LINKED ISSUE #3904: nuxt app instance unavailable error on all pages
Sorry for wrongly opened issue. I cannot edit labels. This issue related with ```bridge``` 🙏 

> @antlionguard Thanks - following up with a PR on that mixin: #3900.

There's something broke after this PR. I got this two error in my all pages. @danielroe 

Firstly i got this:
resim

and after refresh i got this:
resim

_Originally posted by @antlionguard in https://github.com/nuxt/framework/issues/3431#issuecomment-1079097686_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves  #3904

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We don't need to call `useNuxtApp` (and indeed cannot) if there is no instance.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/meta/runtime/plugin.ts [hunk 1]
```diff
@@ -14,9 +14,9 @@ const metaMixin = {
   [metaConfig.mixinKey] () {
     const instance = getCurrentInstance()
```
Comment (pi0) [inline packages/nuxt3/src/meta/runtime/plugin.ts:15]: Shall we early return when instance is undefined? 

Current change has similar effect but we do unnecessary operations and it is not clear in code with behavior.
