### PR TITLE
fix(nuxt): don't add macro query to the end of id

### LINKED ISSUE #3488: Issue with using `<script lang="tsx">` in `~/pages`
```
WARN  [SSR] Error transforming /pages/tkvs/index.vue?vue&type=script&lang.tsx&macro=true: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.

  at formatError (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38098:46)
  at TransformContext.error (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38094:19)
  at TransformContext.transform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:69779:22)
  at async Object.transform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:38334:30)
  at async doTransform (node_modules/.pnpm/vite@2.8.5_sass@1.49.9/node_modules/vite/dist/node/chunks/dep-ff3ab196.js:53030:29)
```

_Originally posted by @xiao-e-yun in https://github.com/nuxt/framework/issues/3477#issuecomment-1057283192_

### PR DESCRIPTION
**Pull request by dotoleeoak**
### 🔗 Linked issue

Resolves #3488

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

The query `lang.jsx` of id should be at the end of id, according to https://github.com/vitejs/vite/issues/8473#issuecomment-1148715786
However `&macro=true` is added at the end so that the `lang` query is not parsed expectedly in vite plugins.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
As a workaround, this seems good to me, but also see https://github.com/vitejs/vite/issues/8473#issuecomment-1152880131.

File: packages/nuxt/src/pages/macros.ts [hunk 1]
```diff
@@ -46,7 +46,8 @@ export const TransformMacroPlugin = createUnplugin((options: TransformMacroPlugi
       // with workaround for vue-loader bug: https://github.com/vuejs/vue-loader/pull/1911
       const scriptImport = findStaticImports(code).find(i => parseQuery(i.specifier.replace('?macro=true', '')).type === 'script')
       if (scriptImport) {
-        const specifier = withQuery(scriptImport.specifier.replace('?macro=true', ''), { macro: 'true' })
```
Comment (pi0) [inline packages/nuxt/src/pages/macros.ts:49]: `withQuery` doesn't changes the order by default if we didn't first remove `?macro=true`. /cc @danielroe Was there any reason you used replaced initially?

image

Comment (danielroe) [reply packages/nuxt/src/pages/macros.ts:49]: Ah, very good point. It was to work around another vite issue, where any existing query was not respected. (So id that vite produced was something like `?macro=true?lang=test.jsx`.)

Comment (pi0) [reply packages/nuxt/src/pages/macros.ts:49]: Thanks for explaining. Does the issue exists anymore?

Comment (danielroe) [reply packages/nuxt/src/pages/macros.ts:49]: Ah, I see I was wrong - it was a `vue-loader` bug: https://github.com/vuejs/vue-loader/pull/1911 which still exists with an open PR to fix it. I'll need to check that this PR doesn't introduce a regression with webpack.

File: packages/nuxt/src/pages/macros.ts [hunk 2]
```diff
@@ -46,7 +46,8 @@ export const TransformMacroPlugin = createUnplugin((options: TransformMacroPlugi
...
+        const parsed = parseURL(scriptImport.specifier.replace('?macro=true', ''))
```
Comment (pi0) [inline packages/nuxt/src/pages/macros.ts:49]:
```suggestion
        // https://github.com/vuejs/vue-loader/pull/1911
        // https://github.com/vitejs/vite/issues/8473
        const parsed = parseURL(scriptImport.specifier.replace('?macro=true', ''))
```

**Review by pi0 — APPROVED** [review]
