### PR TITLE
fix(nitro): use `app.assetsPath` for `publicPath`

### LINKED ISSUE #1816: bug: output filename generate error when set `build.publicPath` as the URL.
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `3.0.0-27274229.29599f0`
- Package Manager:  `pnpm@6.17.1`
- Bundler:          `Vite`
- User Config:      `alias`, `srcDir`, `build`, `meta`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@6.8.0`, `@pinia/nuxt@0.1.2`

### Describe the bug

output filename generate error when set `build.publicPath` be the URL.

image

### Reproduction

- set the `build.publicPath`  be a URL.
- nuxi build

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by webfansplz**
### 🔗 Linked issue

close #1816 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nitro/src/build.ts [hunk 1]
```diff
@@ -31,8 +32,9 @@ export async function generate (nitroContext: NitroContext) {
   consola.start('Generating public...')
 
   const clientDist = resolve(nitroContext._nuxt.buildDir, 'dist/client')
+  const useCDN = hasProtocol(nitroContext._nuxt.publicPath, true)
   if (await isDirectory(clientDist)) {
-    await fse.copy(clientDist, join(nitroContext.output.publicDir, nitroContext._nuxt.publicPath))
+    await fse.copy(clientDist, join(nitroContext.output.publicDir, useCDN ? nitroContext._nuxt.cdnDirName : nitroContext._nuxt.publicPath))
```
Comment (danielroe) [inline packages/nitro/src/build.ts:37]: I don't think this should be part of the nitro build process. This is part of however you upload the files to your CDN.

Comment (danielroe) [reply packages/nitro/src/build.ts:37]: These lines are a good pattern for what we should be doing here:
https://github.com/nuxt/framework/blob/15dad0e0394aa889acd862ba98c5e548f4bb1042/packages/schema/src/config/_app.ts#L37-L41

**Review by pi0 — APPROVED** [review]
