### PR TITLE
fix(nuxt3): don't mutate options when unsetting cookie

### LINKED ISSUE #2480: `useCookie` can't set cookies after clearing it
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0`
- Package Manager:  `yarn@3.1.1`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

```js
const cookie = useCookie('test-cookie')
cookie.value = null

function setCookie() {
  cookie.value = 'some value'
}
```

### Describe the bug

we are mutating cookie options here:
https://github.com/nuxt/framework/blob/6a25d3e245a88d3c838dafa643a5210dba625d73/packages/nuxt3/src/app/composables/cookie.ts#L61-L63

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #2480

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When unsetting the cookie, we were mutating the options which mean that any subsequent setting of cookie value would have a `maxAge` of `-1`, which would effectively unset the cookie immediately.

https://github.com/nuxt/framework/blob/6a25d3e245a88d3c838dafa643a5210dba625d73/packages/nuxt3/src/app/composables/cookie.ts#L61-L63

This PR clones the options in the serialize function so we don't mutate the original options object.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/app/composables/cookie.ts [hunk 1]
```diff
@@ -57,7 +57,8 @@ function readRawCookies (opts: CookieOptions = {}): Record<string, string> {
   }
 }
 
-function serializeCookie (name: string, value: any, opts: CookieSerializeOptions = {}) {
+function serializeCookie (name: string, value: any, _opts: CookieSerializeOptions = {}) {
+  const opts = { ..._opts }
```
Comment (pi0) [inline packages/nuxt3/src/app/composables/cookie.ts:61]: Perf: Maybe we could set a flag like `const removeCookie = value === null || value === undefined` and only destructure+merge when is set?

**Review by pi0 — APPROVED** [review]
