### PR TITLE
fix(nuxt3): return render function for `<Head>`

### LINKED ISSUE #1909: Meta Components reports Cannot read properties of null (reading'$nuxt') error
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.12.0`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `yarn@1.22.4`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

`App.vue` or any components

``` vue
<Head>
<Title>Test</Title>
<Meta name="description" content="My page's description" />
</Head>
```

### Describe the bug

Meta Components reports `Cannot read properties of null (reading'$nuxt')` error

image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #1909

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We need to return a render function; default slot isn't always an equivalent function at the time the parent setup is run.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/meta/runtime/components.ts [hunk 1]
```diff
@@ -194,7 +194,7 @@ export const Style = defineComponent({
 // <head>
 export const Head = defineComponent({
   name: 'Head',
-  setup: (_props, ctx) => ctx.slots.default
+  setup: (_props, ctx) => () => ctx.slots.default?.()
```
Comment (pi0) [inline packages/nuxt3/src/meta/runtime/components.ts:197]: Do you mind adding a todo note and case so later on we can add a test?

Comment (danielroe) [reply packages/nuxt3/src/meta/runtime/components.ts:197]: How about I add a test case to the fixture?

**Review by pi0 — APPROVED** [review]
