### PR TITLE
fix(vite): assign different hmr port for each instance

### LINKED ISSUE #3006: vite HMR Broken for <template>
### Environment

- Operating System: `Darwin`
- Node Version:     `v17.3.1`
- Nuxt Version:     `3.0.0-27389502.88da719`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `vite`, `ssr`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Not needed 

### Describe the bug

Changes to CSS are picked up immediately and it was the same to the rest but ever since I upgraded Nuxt3 yesterday (not sure which version I had before) template changes aren't picked up by and HMR is broken for them

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

Fix #3006, Fix partially #1036

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

*Thanks a lot for @danielroe's help!*

The root cause of HMR breakage is because in middleware mode of Vite, the HMR port is fixed to 24678. Which means when you have multiple Vite/Nuxt instances running, it causes the later server to connect to the wrong Websocket instance, making the HMR fail to trigger. This PR makes the port dynamic with the currently available ports.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/vite/src/client.ts [hunk 1]
```diff
@@ -15,6 +16,13 @@ import { devStyleSSRPlugin } from './plugins/dev-ssr-css'
 import { DynamicBasePlugin, RelativeAssetPlugin } from './plugins/dynamic-base'
 
 export async function buildClient (ctx: ViteBuildContext) {
+  // TODO: After nitropack refactor, try if we can resuse the same server port as Nuxt
+  const hmrPortDefault = 24678 // Vite's default HMR port
+  const hmrPort = await getPort({
+    port: hmrPortDefault,
+    ports: Array.from({ length: 20 }, (_, i) => hmrPortDefault + 1 + i)
```
Comment (pi0) [inline packages/vite/src/client.ts:23]: Any reason not just use a random port?

**Review by pi0 — APPROVED** [review]

File: packages/vite/src/client.ts (hunk 1 above)
Comment (antfu) [reply packages/vite/src/client.ts:23]: No, I am just not sure about how random works. Could change it to random if you want to

Comment (pi0) [reply packages/vite/src/client.ts:23]: OS chooses one when port is 0
