### PR TITLE
fix(nuxt3): enable legacy access to $config and static flags

### LINKED ISSUE #1587: using a legacy module that accesses `$config` fails
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.17.3`
- Nuxt Version:     `3.0.0`
- Package Manager:  `yarn@3.1.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

Using a legacy module that accesses `$config` leads to the following error:

```
Accessing runtime config is not yet supported in Nuxt 3.
```

There are also other APIs we could connect up.

### Reproduction

N/A

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #1587

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR aims to provide compatible APIs for legacy modules that rely on certain flags from [the Nuxt context](https://nuxtjs.org/docs/2.x/internals-glossary/context).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/app/legacy.ts [hunk 1]
```diff
@@ -123,6 +116,15 @@ const todo = new Set<keyof LegacyContext | keyof LegacyContext['ssrContext']>([
 
 const routerKeys: Array<keyof LegacyContext | keyof LegacyContext['ssrContext']> = ['route', 'params', 'query']
 
+const staticFlags = {
+  isClient: process.client,
+  isServer: process.server,
+  isDev: process.dev,
+  isStatic: false,
+  target: 'server',
+  modern: true
```
Comment (pi0) [inline packages/nuxt3/src/app/legacy.ts:125]: (or `undefined`)
```suggestion
  modern: false 
```

File: packages/nuxt3/src/app/legacy.ts [hunk 2]
```diff
@@ -123,6 +116,15 @@ const todo = new Set<keyof LegacyContext | keyof LegacyContext['ssrContext']>([
 
 const routerKeys: Array<keyof LegacyContext | keyof LegacyContext['ssrContext']> = ['route', 'params', 'query']
 
+const staticFlags = {
+  isClient: process.client,
+  isServer: process.server,
+  isDev: process.dev,
+  isStatic: false,
```
Comment (pi0) [inline packages/nuxt3/src/app/legacy.ts:123]: This will make issues with modules depend on `isStatic` for their behavior like image module

Comment (pi0) [reply packages/nuxt3/src/app/legacy.ts:123]:
```suggestion
  isStatic: undefined,
```
