### PR TITLE
fix(nuxt): `useRequestHeaders` type should allow for undefined values

### LINKED ISSUE #5746: useRequestHeaders typing incorrect
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-rc.4`
- Package Manager:  `npm@8.1.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

[GitHub repo link](https://github.com/maxtomczyk/use-request-headers-repro)

To reproduce the bug just start the reproduction project and run `curl localhost:3000`

### Describe the bug

Type for example header cookie is string:

image

However, if I hit localhost:3000 with basic curl request (without `cookie` header set) cookie will be undefined, so the typing is correct only if header will be provided. I think it's important to fix `useRequestHeaders` return type as it can be misleading in some cases (for example kubernetes liveness probe as it happened to me).

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5746

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This explicitly adds `undefined` as a possible value of the return type. This will only have effect if users are using TypeScript in strict mode, as is best practice.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/composables/ssr.ts [hunk 1]
```diff
@@ -3,8 +3,8 @@ import type { CompatibilityEvent } from 'h3'
 import { useNuxtApp } from '#app'
 import { NuxtApp } from '#app/nuxt'
 
-export function useRequestHeaders<K extends string = string> (include: K[]): Record<K, string>;
-export function useRequestHeaders (): Readonly<Record<string, string>>;
+export function useRequestHeaders<K extends string = string> (include: K[]): Record<K, string | undefined>
+export function useRequestHeaders (): Readonly<Record<string, string | undefined>>
```
Comment (pi0) [inline packages/nuxt/src/app/composables/ssr.ts:7]: I might be wrong but isn't fallback an empty object? [src](https://github.com/nuxt/framework/blob/aa9950cfb352060b3c2294beb7b015465705d5d8/packages/nuxt/src/app/composables/ssr.ts#L9)

Comment (danielroe) [reply packages/nuxt/src/app/composables/ssr.ts:7]: Yes. That is what this types.
