### PR TITLE
fix(nuxt)!: include request url and params in `useFetch` key

### LINKED ISSUE #6361: Page Route not refresh the template request data
### Environment

Nuxt CLI v3.0.0-rc.6 
------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.12.1`
- Builder:          `vite`
- User Config:      `components`, `modules`, `css`, `plugins`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.4`, `@nuxtjs/color-mode@3.0.3`, `nuxt-lodash@2.2.0`
- Build Modules:    `-`
------------------------------

### Reproduction

npm run dev

[stackblitz link](https://stackblitz.com/edit/nuxt-starter-uwg9ug)

### Describe the bug

Page Route not refresh the template request data
When I link to jump to another page
 I don't have this problem when I use version 3.0.0-rc.1
Upgrade to 3.0.0-rc.6 There will be this problem
useFetch request { data }  data  not refresh (Always the first requested data)
Is the method changed?
I use usefetch to request

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #6361, resolves https://github.com/nuxt/framework/issues/6365

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

A regression of https://github.com/nuxt/framework/pull/4955 - we were not using the URL as a key if it was provided. This PR uses the url as default key (including params and baseURL if provided).

There is still room for future improvement here via https://github.com/nuxt/framework/issues/6629, for example, and I'll be following up with some more PRs targeting specific issues.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Any update on this @danielroe ? Last time we discussed i think we decided to combination of auto key and hash.

**Comment by danielroe** [comment]
@pi0 Sure! Would you summarise what the issues are from your point of view, apart from hashing the url key?

**Comment by pi0** [comment]
Async data key to be `{autokey}-{hash(input)}`

**Comment by danielroe** [comment]
How about instead: `options.key || ((no functional options) ? hash(url + options) : autoKey)`?

The reason is that any hash of input options is going to mismatch between server + client if any of those options are functions.

**Comment by pi0** [comment]
By hash i mean url+query only not all options.

seems good idea to allow entirely overriding with custom key 👍

**Comment by danielroe** [comment]
excellent

File: packages/nuxt/src/app/composables/fetch.ts [hunk 1]
```diff
@@ -44,7 +46,7 @@ export function useFetch<
   arg2?: string
 ) {
   const [opts = {}, autoKey] = typeof arg1 === 'string' ? [{}, arg1] : [arg1, arg2]
-  const _key = opts.key || autoKey
+  const _key = opts.key || (typeof request === 'string' ? hash(withBase(unref(opts.baseURL) || '', withQuery(request as string, unref(opts.params) || {}))) : autoKey)
```
Comment (pi0) [inline packages/nuxt/src/app/composables/fetch.ts:49]: (didn't locally tested) We can pass raw object to hash function. I guess also withBase not needed we mainly need digest.

```suggestion
  const _reqHash = typeof request === 'string' ? hash([unref(opts.baseURL)]) : ''
  const _key = opts.key || (autoKey + '-' + (typeof request === 'string' ? hash([request, unref(opts.baseURL), unref(opts.params)]) : ''))
```

Comment (danielroe) [reply packages/nuxt/src/app/composables/fetch.ts]: updated. though seems like this approach would prevent sharing useFetch state between pages?

**Review by pi0 — APPROVED** [review]

**Comment by examgoal** [comment]
The fetch options key not working anymore! I think it broke it, please check again

**Comment by manniL** [comment]
@examgoal Please create a new issue with reproduction ☺️
