### PR TITLE
fix(nuxt3): re-enable tree-shaking `definePageMeta`

### LINKED ISSUE #3175: Improve warning about `definePageMeta()` outside `setup`
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27408580.aece351`
- Package Manager:  `npm@8.1.2`
- Bundler:          `Vite`
- User Config:      `target`, `head`, `srcDir`, `css`, `plugins`, `components`, `buildModules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

```vue
<script lang="ts">
definePageMeta({
  layout: 'hero'
})

export default defineComponent({
 // ...
})
</script>
```

### Describe the bug

In a recent update, a new warn has been added when using `definePageMeta()` outside the `setup()` method. But it's a bit misleading, as it insinuates that it's *only* usable inside `<script setup>`. But it is indeed possible inside
```ts
export default defineComponent({
  setup () {
    definePageMeta({
      layout: false
    })
  },
  // ....
})
```

### Additional context

Output of `npm run dev`
```
✔ Nitro built in 129 ms
definePageMeta() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.
✔ Vite server built in 416ms                      
```

Causing lines:
https://github.com/nuxt/framework/blob/68a227af037cc7c91b00787cadbd2653676e00ad/packages/nuxt3/src/pages/runtime/composables.ts#L27-L29

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #3175

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This follows up on #3150 - I missed the fact that when we early return, we've potentially also changed code. This is also the cause of the new warning people are receiving about using `definePageMeta` outside of setup.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/pages/macros.ts [hunk 1]
```diff
@@ -27,7 +28,9 @@ export const TransformMacroPlugin = createUnplugin((options: TransformMacroPlugi
         }
       }
 
-      if (!parseQuery(search).macro) { return }
+      if (!parseQuery(search).macro) {
+        return originalCode === code ? undefined : code
```
Comment (pi0) [inline packages/nuxt3/src/pages/macros.ts:32]: Side note: Doesn't rollup expect `null` instead of `undefined`? (however I think both behave similar)

**Review by pi0 — APPROVED** [review]
