### PR TITLE
fix(nuxt3): enable app-level `<suspense>` with pages module

### LINKED ISSUE #1344: Could I fetch data (or perform some asynchronous tasks) in layout setup?
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v14.18.1`
- Nuxt Version:     `3.0.0-27247485.fb4359e`
- Package Manager:  `Yarn`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Describe the bug

When navigating between pages inherited from different layouts,

And some layouts need to get something or perform other asynchronous tasks,

It will end with a blank page.

### Reproduction

1. Start with `yarn dev`
2. Go to http://localhost:3000/
3. Click `Layout` link

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #1893: async app in combination with vue-router breaks reactivity
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.0.1`
- Nuxt Version:     `3.0.0-27277498.850ef69`
- Package Manager:  `npm@8.1.3`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/async-app-vue-t7b5b

### Describe the bug

using top-level await in app.vue, in combination with vue-router, breaks reactivity

```vue
<script setup>
const active = ref(false)

await Promise.resolve()
</script>

<button @click='active = !active'>{{ active }}</button>
```

### Additional context

pages directory needs to be present for vue router to be initiated.
removing either the await statement or the pages directory resolves the bug.

i think fixing this bug would make for a good vuex replacement, becuase one could just use vue's provide / inject feature from the project root.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #1893
resolves #1344

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Context is #750. Even with pages module enabled (which handles suspensible lIt seems we need a top-level `<Suspense>` barrier outside to cover await within `app` and layouts.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/pages/module.ts [hunk 1]
```diff
@@ -29,8 +29,6 @@ export default defineNuxtModule({
     })
 
     nuxt.hook('app:resolve', (app) => {
-      // Remove default root with Suspense
-      app.rootComponent = resolve(runtimeDir, 'root.vue')
```
Comment (pi0) [inline packages/nuxt3/src/pages/module.ts:33]: Should we remove `root.vue` in this case then?

Comment (danielroe) [reply packages/nuxt3/src/pages/module.ts:33]: Yes 🙈
