### PR TITLE
fix: nitropack fixes and upgrade to 0.2.x

### LINKED ISSUE #4173: Can't import files from project when adding serverMiddleware from module
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27488954.9fbb9be`
- Package Manager:  `yarn@1.22.10`
- Builder:          `vite`
- User Config:      `modules`, `build`
- Runtime Modules:  `@/modules/testModule`, `@nuxtjs/tailwindcss@5.0.2`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/Rigo-m/sb-nuxt-types-repro

See `modules/testModule/runtime/test.ts`

### Describe the bug

`Rollup error:  Could not load ***/sb-types-repro/server/config/someConfig (imported by modules/testModule/runtime/test.ts): ENOENT: no such file or directory, open '***/sb-types-repro/server/config/someConfig'`

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #4179: Vercel build preset doesn't output to correct folder in latest nuxt3 version
### Environment

Any nuxt3 env with latest version will work. Here is the stackblitz one : 

```
RootDir: /home/projects/github-wgbemg
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27489107.7379184`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

To reproduce the issue, simply run `NITRO_PRESET=vercel npm run build`. Instead of having a `.vercel_ouput_build` folder you have the classic `.output` folder. However, the entry point `vercel.mjs` is there.

You can use this [stackblitz](https://stackblitz.com/edit/github-wgbemg?file=nuxt.config.ts) reproduction link to run the command.

### Describe the bug

The vercel preset create a `.output` directory instead of a `.vercel_ouput_build` directory.

### Additional context

_No response_

### Logs

```shell
❯ NITRO_PRESET=vercel npm run build
$ nuxi build
Nuxt CLI v3.0.0-27489107.7379184
ℹ Client built in 1309ms
ℹ Building server...
✔ Server built in 645ms
✔ Generated public .output/static
start Building server...
ℹ Vite client warmed up in 2378ms
start Writing server bundle...
✔ Server built
  ├─ .output/functions/node/server/package.json (346 B) (198 B gzip)
  ├─ .output/functions/node/server/index.mjs (275 B) (164 B gzip)
  ├─ .output/functions/node/server/chunks/vue3.mjs (283 B) (197 B gzip)
  ├─ .output/functions/node/server/chunks/nitro/vercel.mjs (10.3 kB) (3.48 kB gzip)
  ├─ .output/functions/node/server/chunks/index.mjs (395 kB) (91 kB gzip)
  ├─ .output/functions/node/server/chunks/handlers/renderer.mjs (23.4 kB) (6.47 kB gzip)
  ├─ .output/functions/node/server/chunks/app/server.mjs (153 kB) (39.5 kB gzip)
  └─ .output/functions/node/server/chunks/app/client.manifest.mjs (271 B) (181 B gzip)
Σ Total size: 1.01 MB (248 kB gzip)
```

### PR DESCRIPTION
**Pull request by pi0**
Fixes regarding nitropack:

- avoid overriding nitro's output dir (resolves #4179)
- provide nuxt aliases (resolves #4173)
- update nitropack to 0.2.x (related to #4177) inlining nuxt related stuff

### CODE REVIEW

File: packages/vite/src/server.ts [hunk 1]
```diff
@@ -82,7 +82,8 @@ export async function buildServer (ctx: ViteBuildContext) {
 
   await ctx.nuxt.callHook('vite:extendConfig', serverConfig, { isClient: false, isServer: true })
 
-  ctx.nuxt.hook('nitro:generate', async () => {
+  // TODO: Do we still need this?
+  ctx.nuxt.hook('build:done', async () => {
```
Comment (pi0) [inline packages/vite/src/server.ts:86]: /cc @danielroe Do we still need this? Also any reason not using `build:done` hook? It is called almost at same lifecycle and `nitro:generate` hook is removed.

Comment (pi0) [reply packages/vite/src/server.ts:86]: (merging as hotfix. let's hope if fine)
