### PR TITLE
fix(nuxt): always write nitro types when building

### LINKED ISSUE #6024: auto import is not working on server directory codes when build
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.14.0`
- Builder:          `vite`
- User Config:      `typescript`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

add this to nuxt.config.ts

`typescript: {
    strict: true,
    typeCheck: true,
  },`

npm run build is fail with below message

`ERROR(TypeScript)  Cannot find name 'defineEventHandler'.`

### Describe the bug

ERROR(TypeScript)  Cannot find name 'defineEventHandler'.

1 | export default defineEventHandler(async (event) => {
   |                ^^^^^^^^^^^^^^^^^^
2 |     return 'test !'
3 | })
4 |

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #6024

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

If users are checking types on build, we should write `nitro.d.ts` then as well.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/nitro.ts [hunk 1]
```diff
@@ -141,7 +141,7 @@ export async function initNitro (nuxt: Nuxt) {
 
   // Add typed route responses
   nuxt.hook('prepare:types', async (opts) => {
-    if (nuxt.options._prepare) {
+    if (nuxt.options._prepare || !nuxt.options.dev) {
```
Comment (pi0) [inline packages/nuxt/src/core/nitro.ts:144]: Do we have `dev: true` + `_prepare: true` situation? If not maybe we can simplify condition?

Comment (danielroe) [reply packages/nuxt/src/core/nitro.ts:144]: We also want to write types in development.

**Review by pi0 — APPROVED** [review]
