### PR TITLE
fix(nuxt3): warn if builder can't be loaded

### LINKED ISSUE #3759: Builder webpack option, script dev is failed
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.13.2`
- Nuxt Version:     `3.0.0-27439932.78761c2`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `builder`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

Code sendbox: https://codesandbox.io/s/sharp-booth-z4m7jb?file=/nuxt.config.ts

### Describe the bug

When i nuxt.config.ts option changed `builder: 'webpack'`, dev and build script is failed.
```
 ERROR  Cannot start nuxt:  Cannot destructure property 'bundle' of '(intermediate value)(intermediate value)(intermediate value)' as it is undefined.

  at bundle (node_modules/nuxt3/dist/chunks/index.mjs:1379:19)
  at async build (node_modules/nuxt3/dist/chunks/index.mjs:1355:5)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6734:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6771:5)
  at async _main (node_modules/nuxi/dist/chunks/index.mjs:384:7)
```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #3759

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds a better error when `@nuxt/webpack-builder` can't be resolved in the project.

```
 ERROR  Cannot start nuxt:  [nuxt] Could not load @nuxt/webpack-builder. Is it in your project dependencies?        09:42:31

  at bundle (packages/nuxt3/src/core/builder.ts:64:13)
  at async build (packages/nuxt3/src/core/builder.ts:30:5)
  at async Promise.all (index 1)
  at async load (packages/nuxi/src/commands/dev.ts:53:9)
  at async Object.invoke (packages/nuxi/src/commands/dev.ts:97:5)
  at async _main (packages/nuxi/src/cli.ts:37:7)

```

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/core/builder.ts [hunk 1]
```diff
@@ -55,10 +55,15 @@ function watch (nuxt: Nuxt) {
...
-  const { bundle } = typeof nuxt.options.builder === 'string'
-    ? await tryImportModule(nuxt.options.builder, { paths: nuxt.options.rootDir })
-    : nuxt.options.builder
   try {
+    const { bundle } = typeof nuxt.options.builder === 'string'
+      ? await tryImportModule(nuxt.options.builder, { paths: nuxt.options.rootDir }) || {}
+      : nuxt.options.builder
+
+    if (!bundle) {
+      throw new Error(`[nuxt] Could not load \`${nuxt.options.builder}\`. Is it in your project dependencies?`)
```
Comment (pi0) [inline packages/nuxt3/src/core/builder.ts:64]: This message can be misleading. First that importing might fail because of of any other issue and second, installing should be `@nuxt/webpack-builder-edge` aliased to `@nuxt/webpack-builder` (at least at the moment). We could make a hand picked message like the one in breaking changes.

Comment (danielroe) [reply packages/nuxt3/src/core/builder.ts]: New output:

```bash
 ERROR  Cannot start nuxt:  Could not load @nuxt/webpack-builder. You may need to add it to your project dependencies, following the steps in https://github.com/nuxt/framework/pull/2812.

  at bundle (packages/nuxt3/src/core/builder.ts:68:13)
  at async build (packages/nuxt3/src/core/builder.ts:30:5)
  at async Promise.all (index 1)
  at async load (packages/nuxi/src/commands/dev.ts:53:9)
  at async Object.invoke (packages/nuxi/src/commands/dev.ts:97:5)
  at async _main (packages/nuxi/src/cli.ts:37:7)
  ```

  Another error will look like:

```
   ERROR  Cannot start nuxt:  Some other error message                                12:01:12
Require stack:
- /Users/daniel/code/nuxt/framework/index.js

  Require stack:
  - index.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
  at Function.resolve (internal/modules/cjs/helpers.js:99:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:192841)
  at resolveModule (packages/kit/src/internal/cjs.ts:87:41)
  at importModule (packages/kit/src/internal/cjs.ts:128:24)
  at bundle (packages/nuxt3/src/core/builder.ts:60:33)
  at build (packages/nuxt3/src/core/builder.ts:30:11)
  at async Promise.all (index 1)
  at async load (packages/nuxi/src/commands/dev.ts:53:9)
  at async Object.invoke (packages/nuxi/src/commands/dev.ts:97:5)
  ```

**Review by pi0 — APPROVED** [review]
LGTM. We might offer better automated behavior with nypm...
