### PR TITLE
fix(pages): ignore expression delimiters within quotes

### LINKED ISSUE #5862: DefinePageMeta formatting error when converting to const meta
### Environment

- Operating System: `Linux`
- Node Version: `v16.13.1`
- Nuxt Version: `3.0.0-rc.4`
- Package Manager: `pnpm@7.5.0`
- Builder: `vite`
- User Config: `typescript`

### Reproduction

``<script setup lang="ts">
    definePageMeta({
        title: 'La base données graphique qui s\'inspire du réel - Kubix'
    });
</script>``

### Describe the bug

When i use definePageMeta in the script setup, this is what the console shows:

[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /home/nelson/Documents/dev/frontend/nuxt-app/pages/index.vue?macro=true
  39 |  export const meta = {
  40 |        title: "La base donn\xE9es graphique qui s'inspire du r\xE9el - Kubix"
  41 |      });
     |       ^
  42 |      const __returned__ = {};
  43 |      Object.defineProperty(__returned__, "__isScriptSetup", { enumerable: false, value: true });

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5862

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR fixes an oversight in the original code, which followed nesting within quotes.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/pages/macros.ts [hunk 1]
```diff
@@ -107,7 +109,7 @@ function extractObject (code: string) {
   do {
     if (stack[0] === code[0] && result.slice(-1) !== '\\') {
       stack.shift()
-    } else if (code[0] in starts) {
+    } else if (code[0] in starts && !quotes.includes(stack[0])) {
```
Comment (pi0) [inline packages/nuxt/src/pages/macros.ts:112]: (small)Perf: Shall we use a regex instead?

Comment (danielroe) [reply packages/nuxt/src/pages/macros.ts:112]: 👍 Oh the temptation to make it a magic one. 😆

**Review by pi0 — APPROVED** [review]
