### PR TITLE
fix(nuxt): update `class` prop type for head components

### LINKED ISSUE #9118: Html and Body components: class prop type error if not string
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@vueuse/nuxt@9.5.0`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-fbh4ex?file=app.vue

**Please note:** the StackBlitz version doesn't show type errors. If you have a fresh local project with the code, you will see the type error.

### Describe the bug

The `<Html>` and `<Body>` components show type errors when you attempt to use anything other than a string for the `class` prop. Shouldn't their `class` prop accept arrays and objects as well?

```
(property) class?: string | undefined
Type '{ test: true; }' is not assignable to type 'string'.ts(2322)
components.d.ts(654, 5): The expected type comes from property 'class' which is declared here on type 'ComponentProps<DefineComponent<{ manifest: StringConstructor; version: StringConstructor; xmlns: StringConstructor; renderPriority: (StringConstructor | NumberConstructor)[]; ... 27 more ...; translate: StringConstructor; }, ... 10 more ..., { ...; }>>'
```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by okakyo**
### 🔗 Linked issue

#9118 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

resolve #9118 - Add an `Object` to html and body class prop to solve a type error.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Thanks!

File: packages/nuxt/src/head/runtime/components.ts [hunk 1]
```diff
@@ -26,7 +26,7 @@ const globalProps = {
     type: Boolean,
     default: undefined
   },
-  class: String,
+  class: [String, Object],
```
Comment (danielroe) [inline packages/nuxt/src/head/runtime/components.ts:29]:
```suggestion
  class: [String, Object, Array],
```
