### PR TITLE
fix(vite): handle emitted assets with relative urls and dynamic base

### LINKED ISSUE #2777: src: url("assets/fonts/my-font.ttf") rewritten to '__NUXT_BASE__/my-font.ttf' in production build
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v17.3.1`
- Nuxt Version:     `3.0.0-27375427.d07d572`
- Package Manager:  `yarn@3.2.0-rc.10`
- Bundler:          `Vite`
- User Config:      `publicRuntimeConfig`, `privateRuntimeConfig`, `buildModules`, `css`, `vite`, `unocss`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.5.3`, `unplugin-icons/nuxt`, `@unocss/nuxt@0.22.4`
------------------------------

### Reproduction

...

### Describe the bug

I suspect this may be related to #2655. 

It only affects `yarn build`.

``` css
@font-face {
    font-family: "SpaceGroteskLight";
    src: url("assets/fonts/SpaceGrotesk-Light.ttf");
    font-display: swap;
}
```

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #2777

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR handles two issues with the recently merged support for dynamic base URLs in Vite.

1. CSS assets are rewritten to use relative imports
2. required assets are rewritten dynamically (we can't replace in transform because of the `__VITE_ASSET` map that is used by vite asset plugin).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/vite/src/plugins/dynamic-base.ts [hunk 1]
```diff
@@ -1,18 +1,45 @@
...
 }
 
+const escapeRE = (str: string) => str.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&')
+
+export const RelativeAssetPlugin = function (): Plugin {
+  return {
+    name: 'nuxt:vite-relative-asset',
+    generateBundle (_, bundle) {
+      const generatedAssets = Object.entries(bundle).filter(([_, asset]) => asset.type === 'asset').map(([key]) => escapeRE(key))
+      const assetRE = new RegExp(`\\/__NUXT_BASE__\\/(${generatedAssets.join('|')})`, 'g')
```
Comment (pi0) [inline packages/vite/src/plugins/dynamic-base.ts:17]: Is it fine not escaping asset names? (eg `.` in name): `new RegExp('foo.bar').test('foo_bar') => true`

Comment (danielroe) [reply packages/vite/src/plugins/dynamic-base.ts:17]: I was thinking more of directory slashes, which would be fatal.

**Comment by danielroe** [comment]
This also implements this suggestion: https://github.com/nuxt/framework/pull/2655#discussion_r782450085 😁

**Comment by eMeRiKa13** [comment]
It didn't fixed the problem for me.

In production I now have `/_nuxt/image.png`, but I should have `/_nuxt/assets/image.png`

**Comment by danielroe** [comment]
@eMeRiKa13 Would you raise a new issue with a reproduction please?

**Comment by eMeRiKa13** [comment]
I tried to use the code sandbox template but I'm too beginner for that... and can't make it work.

**Comment by eMeRiKa13** [comment]
@danielroe I tried to use the code sandbox template but I'm too beginner for that... and can't make it work.

**Comment by danielroe** [comment]
@eMeRiKa13 If you can recreate it locally with a new nuxt project, and push that to GitHub, that would be just as good :+1:

**Comment by eMeRiKa13** [comment]
@danielroe locally it works, I have `/_nuxt/assets/image.png` but on my Vercel deployment I only have `/_nuxt/image.png`
