### PR TITLE
fix(nuxt3): improve component loading behaviour

### LINKED ISSUE #3678: Identifier '__nuxt_component_2' has already been declared
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v14.17.1`
- Nuxt Version:     `3.0.0-27456065.f38cace`
- Package Manager:  `yarn@1.22.5`
- Builder:          `vite`
- User Config:      `meta`, `css`, `buildModules`, `build`, `vite`, `publicRuntimeConfig`, `unlighthouse`, `router`, `sitemap`, `serverMiddleware`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@7.7.0`, `vue-plausible@1.3.1`, `@unlighthouse/nuxt@0.3.6`, `~/modules/sitemap`
------------------------------

### Reproduction

https://github.com/florian-lefebvre/portfolio

### Describe the bug

After updating to the last version of nuxt3 (see environment), I get this error related to SSR transforming for a previously working composable (see logs.)

### Additional context

Not necessary, related to https://github.com/nuxt/framework/issues/3654 and https://github.com/nuxt/framework/issues/3666.

### Logs

```shell
√ Vite server built in 6162ms                                                                                                                             20:45:00
√ Sitemap generated                                                                                                                                       20:45:00
√ Nitro built in 299 ms                                                                                                                                   20:45:00

 WARN  [SSR] Error transforming D:/DEV/PROJECTS/PERSO/florian-lefebvre.dev/portfolio/pages/index.vue: Parse failure: Identifier '__nuxt_component_2' has already been declared (2:322)
Contents of line 2: import useSeo from '/composables/useSeo.ts';import { default as __nuxt_component_0 } from "/components/Container.vue";import { default as __nuxt_component_1 } from "/components/HeroAtomAnimation.vue";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_3 } from "/components/Projects/Swiper.vue";

  Contents of line 2: import useSeo from '/composables/useSeo.ts';import { default as __nuxt_component_0 } from "/components/Container.vue";import { default as __nuxt_component_1 } from "/components/HeroAtomAnimation.vue";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_3 } from "/components/Projects/Swiper.vue";
  at ssrTransform (node_modules\vite\dist\node\chunks\dep-9c153816.js:52135:15)
  at doTransform (node_modules\vite\dist\node\chunks\dep-9c153816.js:53052:48)

√ Vite server built in 695ms                                                                                                                              20:45:01
You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.
i [I18N] Setup plugin
[Vue Router warn]: uncaught error during route navigation:
i [SWIPER] Registering components
i [VUE3-MQ] Setup plugin
i [I18N] Setup plugin
i [SWIPER] Registering components
i [VUE3-MQ] Setup plugin
TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
Cannot read property '__vccOpts' of undefined
  at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
(node:28512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:28512) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:28512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
(node:28512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
i [I18N] Setup plugin
[Vue Router warn]: uncaught error during route navigation:
i [SWIPER] Registering components
i [VUE3-MQ] Setup plugin
i [I18N] Setup plugin
i [SWIPER] Registering components
i [VUE3-MQ] Setup plugin
TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Cannot read property '__vccOpts' of undefined
  at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:28512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:28512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:28512) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__vccOpts' of undefined
    at D:\DEV\PROJECTS\PERSO\florian-lefebvre.dev\portfolio\node_modules\vue-router\dist\vue-router.cjs.js:2026:55
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:28512) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)

 WARN  Duplicated imports "definePageMeta", the one from "D:/DEV/PROJECTS/PERSO/florian-lefebvre.dev/portfolio/node_modules/nuxt3/dist/pages/runtime/composables" has been ignored


n declared (2:322)
Contents of line 2: import useSeo from '/composables/useSeo.ts';import { default as __nuxt_component_0 } from "/components/Container.vue";import { default as __nuxt_component_1 } from "/components/HeroAtomAnimation.vue";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_3 } from "/components/Projects/Swiper.vue";

  Contents of line 2: import useSeo from '/composables/useSeo.ts';import { default as __nuxt_component_0 } from "/components/Container.vue";import { default as __nuxt_component_1 } from "/components/HeroAtomAnimation.vue";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_2 } from "/node_modules/nuxt3/dist/app/components/nuxt-link.mjs";import { default as __nuxt_component_3 } from "/components/Projects/Swiper.vue";
  at ssrTransform (node_modules\vite\dist\node\chunks\dep-9c153816.js:52135:15)
  at doTransform (node_modules\vite\dist\node\chunks\dep-9c153816.js:53052:48)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #3678, resolves https://github.com/nuxt/framework/issues/3739

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

* Vue can call resolveComponent more than once when kebab + pascal case are both used in template. This deduplicates imports with a Set.
* We also convert to pascal case when resolving as there is an edge case with numbers and the following are all valid ways of referring to the same component in Vue: `<Oscars2022>`, `<oscars-2022>` and `<oscars2022>`
* I also spotted an opportunity to use the helper function from Vue 3 rather than a copy of it.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/components/loader.ts [hunk 1]
```diff
@@ -24,13 +25,14 @@ export const loaderPlugin = createUnplugin((options: LoaderOptions) => ({
   }
 }))
 
-function findComponent (components: Component[], name:string) {
-  return components.find(({ pascalName, kebabName }) => [pascalName, kebabName].includes(name))
+function findComponent (components: Component[], name: string) {
+  const id = pascalCase(name)
```
Comment (pi0) [inline packages/nuxt3/src/components/loader.ts:29]: Not sure what was main issue but we are normalizing " and ' in names within component scanner for `pascalName`: 

```suggestion
  const id = pascalCase(name).replace(/["']/g, '')
```

Comment (danielroe) [reply packages/nuxt3/src/components/loader.ts]: I'm not sure it's possible for a name to have these characters in at this point in the lifecycle, but it doesn't hurt.
