### PR TITLE
fix(nuxt): resolve plugins and middleware to their full path

### LINKED ISSUE #6300: i18n/useRouter/useNuxtApp - Error nuxt instance unavailable
### Environment

- Operating System: `Linux`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `css`, `head`, `i18n`, `modules`, `target`, `telemetry`, `titleTemplate`
- Runtime Modules:  `@nuxtjs/i18n@8.0.0-alpha.0-27654621.987d743`
- Build Modules:    `-`

### Reproduction

https://github.com/max5432112345/nuxt-error-1

### Describe the bug

I18n with strategy: 'prefix' not work, but without that property work

### Additional context

_No response_

### Logs

```shell
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
  at Module.useNuxtApp (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:415:13)
  at useRouter (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:1168:32)
  at Module.navigateTo (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:1207:18)
  at Module.navigate (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:10818:34)
  at file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:3139:27
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Object.callAsync (file:///Downloads/nuxt3/nuxt-app/node_modules/unctx/dist/index.mjs:45:16)
  at async applyPlugin (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:347:23)
  at async Module.applyPlugins (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:357:5)
  at async createNuxtAppServer (file:///Downloads/nuxt3/nuxt-app/.nuxt/dist/server/server.mjs:46:7)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves  #6300

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When a plugin is in injected like `/path/to/someplugin` without the extension, we can likely match `/path/to/someplugin.*`. A more accurate, but more costly, route would be to use `resolvePath` when adding plugins (or to normalize afterwards before `app:resolve`.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
Is this possible to add a simple usage test fixture?

File: test/fixtures/basic/modules/example.ts [hunk 1]
```diff
@@ -7,5 +8,15 @@ export default defineNuxtModule({
   meta: {
     name: 'my-module',
     configKey: 'sampleModule'
+  },
+  setup () {
+    addPlugin(fileURLToPath(new URL('./runtime/plugin', import.meta.url)))
+    useNuxt().hook('app:resolve', (app) => {
+      app.middleware.push({
+        name: 'unctx-test',
+        path: fileURLToPath(new URL('./runtime/middleware', import.meta.url)),
```
Comment (pi0) [inline test/fixtures/basic/modules/example.ts:17]: Was thinking, what if we could solve it by resolving real path during app resolution. unctx being broken was one example but inconsistencies could happen in other places as well.

Comment (danielroe) [reply test/fixtures/basic/modules/example.ts:17]: Agreed. Will refactor 👍

File: packages/nuxt/src/core/app.ts [hunk 2]
```diff
@@ -109,8 +108,21 @@ export async function resolveApp (nuxt: Nuxt, app: NuxtApp) {
       ])
     ].map(plugin => normalizePlugin(plugin as NuxtPlugin)))
   }
-  app.plugins = uniqueBy(app.plugins, 'src')
 
   // Extend app
   await nuxt.callHook('app:resolve', app)
+
+  // Normalize and de-duplicate plugins and middleware
+  app.middleware = uniqueBy(await normalizePaths(app.middleware, 'path'), 'name')
```
Comment (pi0) [inline packages/nuxt/src/core/app.ts:116]: We might do this before `app:resolve` hook as well. Otherwise modules get unpredictable or not normalized values. We should also do after hook again in case, modules did add something not normalized.

**Review by pi0 — APPROVED** [review]

**Comment by max5432112345** [comment]
Deploy failed for nuxt3-docs
Today at 5:11 PM

PR#[6350](https://github.com/nuxt/framework/pull/6350): fix/unctx-plugins@[64a9656](https://github.com/nuxt/framework/commit/64a965677c9b0a0127bdd3ac91592a3fd0be53de)
