### PR TITLE
fix(bridge): exclude bridge alias types to support Volar

### LINKED ISSUE #1920: Volar support for bridge
When generating `tsconfig.json` for Nuxt bridge, we shall set `experimentalCompatMode` that helps work Volar with Vue 2/Bridge out of the box. 

To test: Not sure if volar also resolves `tsconfig.json` with `extend` for `experimentalCompatMode` support or not. /cc @johnsoncodehk

Bonus: Would be nice DX if we can somehow also eliminate requirement of `@vue/runtime-dom` being installed

Refs: (I could find)
- https://github.com/johnsoncodehk/volar/commit/647391f6d72ba7c6d2154c541d5151a0e11b5364
- https://github.com/nuxt/modules/commit/cd127cd879d08be934e0e88e9ec5d634be5d3c6e

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

#1920

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Currently, the Volar support on Bridge is still broken. I think the root cause is that Volar will use the types from `@vue/runtime-core` to resolve the types but we are forced to alias it. 

image

I can confirm locally that removing the selected items will make it work.

Repro: 
- https://github.com/antfu/vitesse-nuxt-bridge
- https://github.com/nuxt/modules

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxi/src/utils/prepare.ts [hunk 1]
```diff
@@ -39,7 +39,13 @@ export const writeTypes = async (nuxt: Nuxt) => {
     '#assets': '@nuxt/nitro'
   }
 
+  // Do not alias types for Vue 3 packages to support Volar
```
Comment (pi0) [inline packages/nuxi/src/utils/prepare.ts:42]:
```suggestion
  // Do not bridge alias types to support Volar
```
