### PR TITLE
fix(nuxt): normalize string transpile paths for windows

### LINKED ISSUE #5257: [windows] package import specifier "#imports" is not defined in package
### Environment

Tested with (first) [**example**](https://github.com/nuxt/framework/tree/main/examples/routing/layouts):
```js
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3-27567768.c1f728e`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `modules`
- Runtime Modules:  `@nuxt/ui@0.1.1`
- Build Modules:    `-`
```

and with custom (second) build:

```js
- Operating System: `Windows_NT`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `css`, `build`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### First 

You get fail if:

1. Clone or download from [**source**](https://github.com/nuxt/framework/tree/main/examples/routing/layouts).
2. npm i
3. npm run dev
4. Success! You get error!

image

You get success run if:

1. Clone...
2. npm i
3. npm run build
4. npm run start
5. Success! Your application is run success (why?)

### Second

> Currently, I can't share with a code to reproduce, but trouble a bit semi with the/a first one. I try create repo with reproduce code ... a bit later.

1. npm i
2. npm run dev
3. Open any page with layout... 
4. Profit! You get error with “invalid layout”
4.1 I do the same as in [**example**](https://github.com/nuxt/framework/tree/main/examples/routing/layouts)

image

### Describe the bug

**When you try run app in dev mode, you get error or your layout won't work.**. In the production (npm run build & npm run start) all work's fine.

### Additional context

1. As I say, I try to make/give a repo with reproduce code for second build/code ...
2. **First** - that is a source code from example, **second** - that is my own code what I wrote. In this source I also use **vuetify** as `plugin/vuetify.ts`.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5257

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This normalises any string transpiles added by modules/user (particularly relevant for Windows support).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by antfu — APPROVED** [review]

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/core/nuxt.ts [hunk 1]
```diff
@@ -125,6 +125,9 @@ async function initNuxt (nuxt: Nuxt) {
 
   await nuxt.callHook('modules:done', { nuxt } as ModuleContainer)
 
+  // Normalize any Windows paths (\ => /)
```
Comment (pi0) [inline packages/nuxt/src/core/nuxt.ts:128]:
```suggestion
  // Normalize windows transpile paths added by modules
```

**Comment by pi0** [comment]
Note for the future: We might find a way that untyped schema normalization can handle the modifications. But probably longer term goal when we had proxy.
