### PR TITLE
fix(nuxt3): directly emit `document.template.mjs`

### LINKED ISSUE #4349: .nuxt/views/document.template.mjs' does not provide an export named 'default'
### Environment

    "@pinia/nuxt": "^0.1.8",
    "@vueuse/nuxt": "^7.4.2",
    "autoprefixer": "^10.4.2",
    "bootstrap-icons": "^1.8.1",
    "daisyui": "^2.0.6",
    "element-plus": "^2.0.2",
    "eslint": "^8.5.0",
    "nuxt3": "^3.0.0-27496606.e43ba6e",
    "pinia": "^2.0.11"

### Reproduction

```
 ERROR  [worker reload] [worker init] The requested module '/Users/mac/.webcode/gin-nuxt/web/.nuxt/views/document.template.mjs' does not provide an export named 'default'

  import htmlTemplate from '.nuxt/views/document.template.mjs';
  ^^^^^^^^^^^^
  SyntaxError: The requested module '.nuxt/views/document.template.mjs' does not provide an export named 'default'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async loadESM (node:internal/process/esm_loader:88:5)
```

### Describe the bug

npm run dev  show this

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #4349

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

In development, there's a danger of breaking the nitro build when we write the document template. As we've split bridge implementation off separately, we can instead write it directly.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/core/nitro.ts [hunk 1]
```diff
@@ -196,13 +195,16 @@ async function resolveHandlers (nuxt: Nuxt) {
 async function writeDocumentTemplate (nuxt: Nuxt) {
   // Compile html template
   const src = resolve(nuxt.options.buildDir, 'views/app.template.html')
-  const dst = src.replace(/.html$/, '.mjs').replace('app.template.mjs', 'document.template.mjs')
+  const dst = resolve(nuxt.options.buildDir, 'views/document.template.mjs')
```
Comment (pi0) [inline packages/nuxt3/src/core/nitro.ts:198]: Since we splitted bridge implementation, I think now we could initially generate `.mjs` version from nuxt templates rather than copy and convert.

**Review by pi0 — APPROVED** [review]
