### PR TITLE
fix(nuxt): update `useFetch` key warning to include any function or blob

### LINKED ISSUE #5690: call `useFecth` with `Blob` as body got error
### Environment

Nuxt CLI v3.0.0-rc.4-27611167.a41644e

### Reproduction

```typescript
useFetch(`/api/any-endpoint`, {
    method: "POST",
    body: new Blob(['any_value']),
  })
```

### Describe the bug

> Error: Hashing Blob objects is currently not supported
Use "options.replacer" or "options.ignoreUnknown"

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5690

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This slightly extends the warning for `useFetch` options to include _any_ function passed to it, or also any Blob. (Though `ohash` will also throw an error if a Blob is passed.)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/app/composables/fetch.ts [hunk 1]
```diff
@@ -26,8 +26,8 @@ export function useFetch<
   request: Ref<ReqT> | ReqT | (() => ReqT),
   opts: UseFetchOptions<_ResT, Transform, PickKeys> = {}
 ) {
-  if (process.dev && opts.transform && !opts.key) {
-    console.warn('[nuxt] You should provide a key for `useFetch` when using a custom transform function.')
+  if (process.dev && !opts.key && Object.values(opts).some(v => typeof v === 'function' || v instanceof Blob)) {
+    console.warn('[nuxt] You should provide a key for `useFetch` when passing options that are not serializable to JSON.')
```
Comment (pi0) [inline packages/nuxt/src/app/composables/fetch.ts:30]:
```suggestion
    console.warn('[nuxt] [useFetch] You should provide a key when passing options that are not serializable to JSON:', opts)
```
