### PR TITLE
fix(test-utils): workaround playwright dynamic import issue with Vite

### LINKED ISSUE #3470: `@nuxt/test-utils`: Using tests utils requires installing playwright
### Environment

```
------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.0`
- Nuxt Version:     `3.0.0-27436017.7b6252a`
- Package Manager:  `npm@7.17.0`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dvdfm1?file=test%2Fbasic.test.ts

### Describe the bug

When using Nuxt test utils to load and start a fixtures, it requires install playwright as dependencies. This happens even when I explicitly  disable `browser` option in `setup` function

```ts
await setup({
    rootDir: fileURLToPath(new URL('./fixtures/basic', import.meta.url)),
    server: true,
    browser: false,
  });
```

Installing `playwright` as dependency or commenting `import('playwright')` from package source will solve the issue and I get green success in test result.

### Additional context

_No response_

### Logs

```shell
❯ test/basic.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/basic.test.ts [ test/basic.test.ts ]
Error: Failed to resolve import "playwright" from "node_modules/@nuxt/test-utils/dist/index.mjs". Does the file exist?
 ❯ formatError node_modules/vite/dist/node/chunks/dep-9c153816.js:38098:46
 ❯ TransformContext.error node_modules/vite/dist/node/chunks/dep-9c153816.js:38094:19
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-9c153816.js:69819:26
 ❯ async TransformContext.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:69959:57
 ❯ async Object.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:38334:30
 ❯ async doTransform node_modules/vite/dist/node/chunks/dep-9c153816.js:53030:29

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  no tests
      Time  2.17s (in thread 0ms, Infinity%)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```
```

### PR DESCRIPTION
**Pull request by farnabaz**
### 🔗 Linked issue
resolve #3470

This is a workaround for dynamic import of `playwright`. See: https://github.com/nuxt/framework/issues/3470#issuecomment-1057224699

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

File: packages/test-utils/src/browser.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ export async function createBrowser () {
 
   let playwright: typeof import('playwright')
   try {
-    playwright = await import('playwright')
+    playwright = await import(String('playwright'))
```
Comment (pi0) [inline packages/test-utils/src/browser.ts:10]:
```suggestion
    // Workround for https://github.com/nuxt/framework/issues/3470
    // TODO: Remove when upstream issue resolved
    playwright = await import(String('playwright'))
```
