### PR TITLE
fix(kit): log module id to the console when import fails

### LINKED ISSUE #8191: [DX] Improve error when added module is no module
### Describe the feature

When adding a npm package to `modules` that actually is not a Nuxt module (but e.g. exports CSS), the error message is rather cryptic:

e.g. ` ERROR  Cannot start nuxt:  expected expression, got ':'                                                 15:56:50`

It would be nice to provide a more readable warning and also hint that the module that is failing might not be a module.

[Repro](https://stackblitz.com/edit/https-github-comnuxtframeworkissues8191?file=nuxt.config.ts)

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://v3.nuxtjs.org/community/contribution).
- [X] Check existing [discussions](https://github.com/nuxt/framework/discussions) and [issues](https://github.com/nuxt/framework/issues).

### PR DESCRIPTION
**Pull request by Araneline**
### 🔗 Linked issue

#8191 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #8191 - in case of error during module require/import it will be printed to the console in the form of 'Error while requiring module {module_name}: {error}'.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/kit/src/internal/cjs.ts [hunk 1]
```diff
@@ -118,10 +118,15 @@ export function requireModule (id: string, opts: RequireModuleOptions = {}) {
...
-  // Try to require
-  const requiredModule = _require(resolvedPath)
+  try {
+    // Try to require
+    const requiredModule = _require(resolvedPath)
 
-  return requiredModule
+    return requiredModule
+  } catch (error: unknown) {
+    console.error(`Error while requiring module \`${id.split('/').pop()}\`: ${error}`)
```
Comment (pi0) [inline packages/kit/src/internal/cjs.ts:127]: Shall we preserve the original module id in the error log?

Comment (Araneline) [reply packages/kit/src/internal/cjs.ts:127]: Original id as I found out is a path to the module in case of not module-module at least. So I decided against printing the whole line, extracting only the last part of the path.

If you believe the whole path string would be better, I can commit that fix.

Comment (pi0) [reply packages/kit/src/internal/cjs.ts:127]: We can use this: `relative(process.cwd(), resolvedPath)` to make log more beatiful:

image

**Comment by pi0** [comment]
Instead of `cjs.ts` util, we might add a try-catch directly to `module/install.ts:45` for better stack trace. The utility in cjs a confusing name it requires a _node module_ while in `install.ts` we have access to user input (not resolved) to show in custom error. It also handles ESM branch.

File: packages/kit/src/internal/cjs.ts (hunk 1 above)
Comment (Araneline) [reply packages/kit/src/internal/cjs.ts]: Definitely. Thank you for pointing in the right direction. Made another commit.

**Comment by Araneline** [comment]
> Instead of `cjs.ts` util, we might add a try-catch directly to `module/install.ts:45` for better stack trace. The utility in cjs a confusing name it requires a _node module_ while in `install.ts` we have access to user input (not resolved) to show in custom error. It also handles ESM branch.

Think I got it. Moved the try-catch block to install.ts and used an unresolved module name in the error.

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks!
