### PR TITLE
fix(schema): extend `NuxtOptions` for nitro & bridge types

### LINKED ISSUE #2126: `NuxtConfig` missing `nitro` type
### Environment

- Operating System: `Darwin`
- Node Version:     `v14.16.1`
- Nuxt Version:     `3.0.0-27294839.7e5e50b`
- Package Manager:  `pnpm@6.17.1`
- Bundler:          `Vite`
- User Config:      `nitro`, `env`, `alias`, `srcDir`, `dev`, `build`, `publicRuntimeConfig`, `buildModules`, `meta`, `css`, `vite`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/core/nuxt@6.9.2`, `@pinia/nuxt@0.1.5`

### Reproduction

-

### Describe the bug

image

Maybe it’s what caused by :

https://github.com/nuxt/framework/commit/4fe1fc881c06a7f1b61e922c42792c26355fccd1

https://github.com/nuxt/framework/commit/4fe1fc881c06a7f1b61e922c42792c26355fccd1

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #2126

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Follow-up on migration to `@nuxt/schema`. I've also changed NuxtConfig to extend NuxtOptions. But this may have been  intentional; let me know if so (cc: @pi0).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/types/config.ts [hunk 1]
```diff
@@ -4,7 +4,7 @@ export interface NuxtOptions extends ConfigSchema { }
 
 type DeepPartial<T> = T extends Record<string, any> ? { [P in keyof T]?: DeepPartial<T[P]> | T[P] } : T
 
-export interface NuxtConfig extends DeepPartial<ConfigSchema> { }
+export interface NuxtConfig extends DeepPartial<NuxtOptions> { }
```
Comment (pi0) [inline packages/schema/src/types/config.ts:7]: Why changing? This was intentional. Both config and internal options extend same base schema but user input is different than normalized options (and module options should be typed by kit wrapper)

Comment (danielroe) [reply packages/schema/src/types/config.ts:7]: I'll add a comment to explain. 👍

Comment (danielroe) [reply packages/schema/src/types/config.ts]: The reason for the PR is that `ConfigSchema` is not exposed and can't be augmented at the moment. If the intent is to augment `ConfigSchema` I can fix that too; just let me know.

Comment (pi0) [reply packages/schema/src/types/config.ts]: The intent is to augment NuxtConfig to type hint `nuxt.config` file. Modules on the other hand should not depend on `nuxt.options` types for their module options but use resolved options type.

File: packages/schema/src/types/config.ts [hunk 2]
```diff
@@ -1,9 +1,11 @@
 import { ConfigSchema } from '../../schema/config'
 
+/** Normalized Nuxt options */
 export interface NuxtOptions extends ConfigSchema { }
 
 type DeepPartial<T> = T extends Record<string, any> ? { [P in keyof T]?: DeepPartial<T[P]> | T[P] } : T
 
+/** User configuration (may be different from normalized NuxtOptions) */
```
Comment (pi0) [inline packages/schema/src/types/config.ts:8]:
```suggestion
/** User configuration in `nuxt.config` file */
```

File: packages/schema/src/types/config.ts [hunk 3]
```diff
@@ -1,9 +1,11 @@
 import { ConfigSchema } from '../../schema/config'
 
+/** Normalized Nuxt options */
```
Comment (pi0) [inline packages/schema/src/types/config.ts:3]:
```suggestion
/** Normalized Nuxt options available as `nuxt.options.*` */
```
