### PR TITLE
fix(nuxi): print resolved public directory after generate

### LINKED ISSUE #7511: Output directory message mismatch confi
### Environment

Nuxt 3.0.0.rc9

### Reproduction

Example: https://stackblitz.com/edit/github-eeaz87?file=nuxt.config.ts
(ctrl+c and run `npm install && npm run generate`)

Setup in `nuxt.config.ts`:
```js
export default defineNuxtConfig({
  target: 'static',
  ssr: true,
  nitro: {
    output: {
      publicDir: 'SHOW_THIS',
    },
  },
  dir: {
    static: 'public',
    public: 'SHOW_THIS',
  },
});
```
See after running command `npm install && npm run generate`:
https://github.com/nuxt/framework/blob/d567a91d7d63c9928d3eb0f2da8ccf76b336a971/packages/nuxi/src/commands/generate.ts#L14

### Describe the bug

Message have hard coded value. Changing setting need change message

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #7511

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Using new useNitro utility (https://github.com/nuxt/framework/pull/7557) we can access the resolved publicDir for nitro and print the relative path to it, rather than hard coding `.output/public`.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxi/src/commands/build.ts [hunk 1]
```diff
@@ -38,5 +40,11 @@ export default defineNuxtCommand({
     })
 
     await buildNuxt(nuxt)
+
+    if (args.prerender) {
+      const dir = nitro?.options.output.publicDir
+      const publicDir = dir ? relative(rootDir, dir) : '.output/public'
```
Comment (pi0) [inline packages/nuxi/src/commands/build.ts:46]: We print CLI logs relative to cwd() so that it is clickable from IDE (at least on best hope).

File: packages/nuxi/src/commands/build.ts [hunk 2]
```diff
@@ -38,5 +40,11 @@ export default defineNuxtCommand({
...
+      consola.success(`You can now deploy \`${publicDir}\` to any static hosting!`)
```
Comment (pi0) [inline packages/nuxi/src/commands/build.ts:47]: Note: This is accurate currently because `--prerender` disables server build but it might be inaccurate in the future if `nuxt build --prerender` outputs hybrid. Would you please add a comment to not forget about this? (or simply i would suggest to keep it in `generate.ts` we can refactor later for different messages

Comment (danielroe) [reply packages/nuxi/src/commands/build.ts:48]: Unfortunately we have to call it here as in generate (after build) `useNitro()` returns null.

Comment (pi0) [reply packages/nuxi/src/commands/build.ts:48]: I see! Okay then let's just keep it in mind for future.

**Review by pi0 — APPROVED** [review]
