### PR TITLE
fix(nuxt3)!: custom response type for `useFetch` using first generic

### LINKED ISSUE #3263: `useFetch` type return
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27415326.3c563fa`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

I use *Visual Studio Code* with *Volar*

### Reproduction

In `app.vue`, I fetch data with `useFetch()`

```vue
<script setup lang="ts">
interface Book {
  title: string
  authors: string[]
  serie?: string
}

const { data } = await useFetch<Book>('/books?per-page=32', {
  baseURL: 'https://bookshelves.ink/api',
  lazy: true,
})
console.log(data.value)
</script>
```

[CodeSandbox](https://codesandbox.io/s/nice-torvalds-zyrqb5) is available.

### Describe the bug

When I want to add type to `useFetch()`, I've an error

> Type 'Book' does not satisfy the constraint 'string'.

```vue
<script setup lang="ts">
const { data } = await useFetch<Book>('/books?per-page=32', {
  baseURL: 'https://bookshelves.ink/api',
  lazy: true,
})
</script>
```

It works with `useAsyncData()`

### Additional context

image

### Logs

_No response_

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

Resolves #3263

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Allow setting custom response type of useFetch using first generic param similar to `$fetch`

Breaking change! If you was already using `useFetch` or `useLazyFetch` with custom type, it needs to be updated:

```diff
--- useFetch<string, ResponseType>(....)
+++ useFetch<ResponseType>(....)
```

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: test/fixtures/basic/tests/types.ts [hunk 1]
```diff
@@ -7,22 +7,27 @@ import { defineNuxtConfig } from '~~/../../../packages/nuxt3/src'
 import { useRouter } from '#imports'
 import { isVue3 } from '#app'
 
+interface TestResponse { message: string }
+
 describe('API routes', () => {
   it('generates types for routes', () => {
     expectTypeOf($fetch('/api/hello')).toMatchTypeOf<Promise<string>>()
     expectTypeOf($fetch('/api/hey')).toMatchTypeOf<Promise<{ foo:string, baz: string }>>()
-    expectTypeOf($fetch('/api/other')).toMatchTypeOf<Promise<unknown>>()
```
Comment (danielroe) [inline test/fixtures/basic/tests/types.ts:14]: Was this deleted intentionally?

**Review by danielroe — APPROVED** [review]
An elegant solution 👌

File: test/fixtures/basic/tests/types.ts [hunk 2]
```diff
@@ -7,22 +7,27 @@ import { defineNuxtConfig } from '~~/../../../packages/nuxt3/src'
 import { useRouter } from '#imports'
 import { isVue3 } from '#app'
 
+interface TestResponse { message: string }
+
 describe('API routes', () => {
   it('generates types for routes', () => {
     expectTypeOf($fetch('/api/hello')).toMatchTypeOf<Promise<string>>()
     expectTypeOf($fetch('/api/hey')).toMatchTypeOf<Promise<{ foo:string, baz: string }>>()
```
Comment (pi0) [inline test/fixtures/basic/tests/types.ts:15]:
```suggestion
    expectTypeOf($fetch('/api/hey')).toMatchTypeOf<Promise<{ foo:string, baz: string }>>()
    expectTypeOf($fetch('/api/other')).toMatchTypeOf<Promise<unknown>>()
```
