### PR TITLE
fix(bridge): set `app.basePath`

### LINKED ISSUE #2790: Build error on fresh Nuxt Bridge project
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.13.1`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `yarn@1.22.17`
- Bundler:          `Webpack`
- User Config:      `bridge`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0-27375427.d07d572`
------------------------------

### Reproduction

https://codesandbox.io/s/github/nuxt/starter/tree/v2-bridge-codesandbox

### Describe the bug

Running bridge on a fresh Nuxt 2 project leads to build error: 

` 
ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'length')                                              
  at normalizeLayer (node_modules/h3/dist/index.mjs:625:36)
  at use (node_modules/h3/dist/index.mjs:580:20)
  at Function.app.use (node_modules/h3/dist/index.mjs:567:35)
  at createDevServer (node_modules/@nuxt/nitro/dist/index.mjs:1796:7)
  at createNuxt2DevServer (node_modules/@nuxt/bridge/dist/chunks/module.mjs:269:18)
  at setupNitroBridge (node_modules/@nuxt/bridge/dist/chunks/module.mjs:163:19)
  at setup (node_modules/@nuxt/bridge/dist/chunks/module.mjs:1054:13)
  at ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:501:29)
`

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #2790

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We changed `basePath` to `baseURL` which is undefined in Nuxt Bridge - we'll need to update [this PR too](https://github.com/nuxt/nuxt.js/pull/10197).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nitro/src/context.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export function getNitroContext (nuxtOptions: NuxtOptions, input: NitroInput): N
       generateDir: nuxtOptions.generate.dir,
       publicDir: resolve(nuxtOptions.srcDir, nuxtOptions.dir.public || nuxtOptions.dir.static),
       serverDir: resolve(nuxtOptions.srcDir, (nuxtOptions.dir as any).server || 'server'),
-      baseURL: nuxtOptions.app.baseURL,
+      baseURL: (nuxtOptions.app as any).basePath /* bridge */ || nuxtOptions.app.baseURL || '/',
```
Comment (pi0) [inline packages/nitro/src/context.ts:143]: What about normalizing in bridge module itself?

Comment (danielroe) [reply packages/nitro/src/context.ts:143]: A better idea.
