### PR TITLE
fix(nuxt3)!: sync route object to currently resolved page

### LINKED ISSUE #4086: suspend route object until route suspense resolves
At the moment the route changes before the route component fully loads ([sandbox](https://stackblitz.com/edit/nuxt3-windicss-bm1znm?file=app.vue)).

We already provide our own `useRoute` composable. We can update our implementation so the `route` object returned continues to show the past route until the route component suspense resolves, so this kind of inconsistency is not present.

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #4086, resolves https://github.com/nuxt/framework/discussions/2459

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [x] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR does two things:

1. correctly resolves the route for use within plugins (previously `useRoute()` did not return the correct route until the plugin lifecycle had fully run)
2. creates a 'suspended' route that mirrors the behaviour of the page component - so it does not resolve to the new route until the page component resolves

I would especially welcome testing on this given the nature of the change.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/pages/runtime/router.ts [hunk 1]
```diff
@@ -52,10 +54,23 @@ export default defineNuxtPlugin((nuxtApp) => {
     get: () => previousRoute.value
   })
 
+  // Allows suspending the route object until page navigation completes
+  const path = process.server ? nuxtApp.ssrContext.req.url : withoutBase(window.location.href, window.location.origin)
```
Comment (pi0) [inline packages/nuxt3/src/pages/runtime/router.ts:58]: Do you know a reference how vue-router internally resolve initial path?

Comment (pi0) [reply packages/nuxt3/src/pages/runtime/router.ts:58]: Does it make sense to somehow reuse same implementation to avoid any possible mismatch?

Comment (danielroe) [reply packages/nuxt3/src/pages/runtime/router.ts:58]: Makes sense. At the moment, we don't support baseURLs with `#` in them (i.e. we just get 404s). Is this a use-case we want to support?

**Comment by Atinux** [comment]
Nice work @danielroe 

It would be nice to test indeed and check if it works when using a nested page too 😊

**Comment by danielroe** [comment]
Tested ✅

**Note**: At the moment, a nested page's async setup doesn't block the loading of the parent, which means it doesn't block the updating of the `route` object. That may be a separate issue to track, but it doesn't seem to be an issue with this PR.

**Comment by misaon** [comment]
@danielroe I fighting with following case:

app.vue
```vue
<template>
  <div>
    <NuxtLayout>
      <NuxtPage/>
    </NuxtLayout>
  </div>
</template>
```

pages/index.vue
```vue
<template>
  <div>
    <NuxtLink to="/hi.html">
      Go to Hi page
    </NuxtLink>
  </div>
</template>
```


pages/[slug].html.vue
```vue
<template>
  <div>
    <h1>Hi</h1>
  </div>
</template>

<script lang="ts" setup>
const route = useRoute()

console.log(route.params)
</script>
```

console:
```js
{}
```

How can i get `slug` param value now after your change?

**Comment by misaon** [comment]
Im going back to `3.0.0-27486179.cb74ab6`
