### PR TITLE
fix(nuxt): fix router redirection on aliased page

### LINKED ISSUE #4920: page alias creates a 301 redirect
### Environment

Nuxt CLI v3.0.0-rc.3                                                    18:33:47
RootDir: /home/projects/github-cvl1uq                                   18:33:53
Nuxt project info:                                                      18:33:53

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-cvl1uq

Go to: https://github-cvl1uq--3000.local-corp.webcontainer.io/page-alias

### Describe the bug

With the newest RC, the aliases started working weird. Instead of showing the page at the URL of the alias, they do 301 redirects.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by huang-julien**
resolve #4920 

### 🔗 Linked issue

#4920 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Using the force option on router replace make vue router use the name key in priority to match and retrieve the router location object resulting in a redirection such as the one described in the linked issue. We should just remove the name key from the object passed to router.replace when using force: true

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/pages/runtime/router.ts [hunk 1]
```diff
@@ -182,8 +182,10 @@ export default defineNuxtPlugin(async (nuxtApp) => {
 
   nuxtApp.hooks.hookOnce('app:created', async () => {
     try {
+      const initialRoute = router.resolve(initialURL)
+      delete initialRoute.name
       await router.replace({
-        ...router.resolve(initialURL),
+        ...initialRoute,
         force: true
```
Comment (danielroe) [inline packages/nuxt/src/pages/runtime/router.ts:189]: Would this work if we just did something like this?

```suggestion
        ...router.resolve(initialURL),
        name: undefined,
        force: true
```

Comment (huang-julien) [reply packages/nuxt/src/pages/runtime/router.ts:189]: yes, vue-router use `if ('name' in location && location.name)` so it works too

**Comment by huang-julien** [comment]
@danielroe i just saw some warning in the CI that did not showed up in local, converting this to draft to confirm that there are not any side-effect

**Comment by huang-julien** [comment]
nvm, it seems that it just disapeared with your suggestion 😄

File: packages/nuxt/src/pages/runtime/router.ts [hunk 2]
```diff
@@ -182,8 +182,11 @@ export default defineNuxtPlugin(async (nuxtApp) => {
 
   nuxtApp.hooks.hookOnce('app:created', async () => {
     try {
+      const initialRoute = router.resolve(initialURL)
+      delete initialRoute.name
```
Comment (danielroe) [inline packages/nuxt/src/pages/runtime/router.ts:186]:
```suggestion
```

File: packages/nuxt/src/pages/runtime/router.ts [hunk 3]
```diff
@@ -184,6 +184,7 @@ export default defineNuxtPlugin(async (nuxtApp) => {
     try {
       await router.replace({
         ...router.resolve(initialURL),
+        name: undefined,
```
Comment (pi0) [inline packages/nuxt/src/pages/runtime/router.ts:187]:
```suggestion
        name: undefined, // #4920, #$4982
```
