### PR TITLE
fix(nuxt): strip non-`.vue` extensions from component types

### LINKED ISSUE #7401: Functional Component has type 'any'
### Environment

nuxi info
------------------------------
- Operating System: `Linux`
- Node Version:     `v18.8.0`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

VSCode + Volar + TakeOver mode 4.8.2

### Reproduction

https://github.com/f3oall/nuxt3-functional-component

### Describe the bug

Autoimported Functional Components have type 'any'.

You can see that I explicitly typed component in reproduction. If it's not a bug and I'm doing something wrong, explanation is welcome.

Screenshot:

image (2)

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #7401

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

As in [other places](https://github.com/nuxt/framework/blob/9db2229f705efaae38e743f3e3e61293956feb29/packages/nuxi/src/utils/prepare.ts#L56), we need to strip file extensions for TS types in imports. In this case, we have to keep `.vue` as volar handles that.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/components/templates.ts [hunk 1]
```diff
@@ -75,7 +75,9 @@ export const componentsTypeTemplate: NuxtTemplate<ComponentsTemplateContext> = {
     const buildDir = nuxt.options.buildDir
     const componentTypes = options.getComponents().map(c => [
       c.pascalName,
-      `typeof ${genDynamicImport(isAbsolute(c.filePath) ? relative(buildDir, c.filePath) : c.filePath, { wrapper: false })}['${c.export}']`
+      `typeof ${genDynamicImport(isAbsolute(c.filePath)
+        ? relative(buildDir, c.filePath).replace(/(?<=\w)\.(?!vue)\w+$/g, '')
+        : c.filePath.replace(/(?<=\w)\.(?!vue)\w+$/g, ''), { wrapper: false })}['${c.export}']`
```
Comment (pi0) [inline packages/nuxt/src/components/templates.ts:80]: Considering also `.ts` imports are without extension, shall we always strip extension for generated types?

File: packages/nuxt/src/components/templates.ts [hunk 2]
```diff
@@ -75,7 +75,9 @@ export const componentsTypeTemplate: NuxtTemplate<ComponentsTemplateContext> = {
     const buildDir = nuxt.options.buildDir
     const componentTypes = options.getComponents().map(c => [
       c.pascalName,
-      `typeof ${genDynamicImport(isAbsolute(c.filePath) ? relative(buildDir, c.filePath) : c.filePath, { wrapper: false })}['${c.export}']`
+      `typeof ${genDynamicImport(isAbsolute(c.filePath)
```
Comment (pi0) [inline packages/nuxt/src/components/templates.ts:78]: Refactor: We could introduce `genTypeImport` / `genDynamicTypeImport` that generates extension stripped imports and option for exception.

**Review by pi0 — APPROVED** [review]

File: packages/nuxt/src/components/templates.ts (hunk 2 above)
Comment (pi0) [reply packages/nuxt/src/components/templates.ts:78]: ~> https://github.com/unjs/knitwork/issues/24
