### PR TITLE
fix(nuxt): don't try to set cookie after redirect

### LINKED ISSUE #5183: [unhandledRejection] Cannot set headers after they are sent to the client
[unhandledRejection] Cannot set headers after they are sent to the client                                                                                                                                                   

  at new NodeError (node:internal/errors:372:5)
  at ServerResponse.setHeader (node:_http_outgoing:576:11)
  at sendError (/H:/nuxt%20projects/trademark/node_modules/h3/dist/index.mjs:216:13)
  at nodeHandler (/H:/nuxt%20projects/trademark/node_modules/h3/dist/index.mjs:375:15)

Due to a problem with dynamic imports, I moved all the resources of the application to the /public folder and now I constantly get this error, what could be the problem?

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5183

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We were trying to set headers after redirect when cookies were used. Alternatively we could check writableEnded but I think it's better to have warning surface in this kind of way.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/composables/cookie.ts [hunk 1]
```diff
@@ -38,8 +38,12 @@ export function useCookie <T = string> (name: string, _opts?: CookieOptions<T>):
         writeServerCookie(useRequestEvent(nuxtApp), name, cookie.value, opts)
       }
     }
-    nuxtApp.hooks.hookOnce('app:rendered', writeFinalCookieValue)
-    nuxtApp.hooks.hookOnce('app:redirected', writeFinalCookieValue)
+    const unhook = nuxtApp.hooks.hookOnce('app:rendered', writeFinalCookieValue)
+    nuxtApp.hooks.hookOnce('app:redirected', (...args) => {
+      // don't write cookie subsequently when app:rendered is called
+      unhook()
+      return writeFinalCookieValue(...args)
```
Comment (pi0) [inline packages/nuxt/src/app/composables/cookie.ts:45]: We are not consuming args right?

Comment (danielroe) [reply packages/nuxt/src/app/composables/cookie.ts:45]: No. Just wrote it this way for forward compatibility.

Comment (pi0) [reply packages/nuxt/src/app/composables/cookie.ts:45]: But it is confusing. Can we please pass them (by name) when actually needed?

Comment (danielroe) [inline packages/nuxt/src/app/composables/cookie.ts:45]:
```suggestion
      return writeFinalCookieValue()
```

File: packages/nuxt/src/app/composables/cookie.ts [hunk 2]
```diff
@@ -38,8 +38,12 @@ export function useCookie <T = string> (name: string, _opts?: CookieOptions<T>):
         writeServerCookie(useRequestEvent(nuxtApp), name, cookie.value, opts)
       }
     }
-    nuxtApp.hooks.hookOnce('app:rendered', writeFinalCookieValue)
-    nuxtApp.hooks.hookOnce('app:redirected', writeFinalCookieValue)
+    const unhook = nuxtApp.hooks.hookOnce('app:rendered', writeFinalCookieValue)
+    nuxtApp.hooks.hookOnce('app:redirected', (...args) => {
```
Comment (danielroe) [inline packages/nuxt/src/app/composables/cookie.ts:42]:
```suggestion
    nuxtApp.hooks.hookOnce('app:redirected', () => {
```

File: packages/nuxt/src/app/composables/cookie.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/app/composables/cookie.ts]: Oh, agreed.
