### PR TITLE
fix(nuxt): do not pass prefetched class to custom link

### LINKED ISSUE #7520: NuxtLink with custom attribute causes vue warning in RC10
### Environment

Nuxi 3.0.0-rc.10
RootDir: /sandbox
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.19.3`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://codesandbox.io/s/jolly-sky-uz9ovm?file=/pages/index.vue

Here's a snippet of the juicy bit:
```
<NuxtLink v-slot="{ href }" to="/foo" custom>
  <a :href="href">Here's a link</a>
</NuxtLink>
```

### Describe the bug

When using a NuxtLink component with custom attribute, a warning is logged.

### Additional context

In RC 8 it was working fine, my suspicion is that the new link prefetching feature is to blame.

Suspicious line of code: https://github.com/nuxt/framework/blob/v3.0.0-rc.10/packages/nuxt/src/app/components/nuxt-link.ts#L229

Maybe worth to mention, a workaround is to use vue router's RouterLink component directly instead of NuxtLink

### Logs

```shell
[Vue warn]: Extraneous non-props attributes (class) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves  #7520

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We shouldn't pass prefetched class to routerlink if it's a custom link. (Later, might be worth thinking about how to pass prefetched class to slot.)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/app/components/nuxt-link.ts [hunk 1]
```diff
@@ -226,7 +226,7 @@ export function defineNuxtLink (options: NuxtLinkOptions) {
             {
               ref: process.server ? undefined : (ref: any) => { el!.value = ref?.$el },
               to: to.value,
-              class: prefetched.value && (props.prefetchedClass || options.prefetchedClass),
+              ...prefetched.value && !props.custom ? { class: props.prefetchedClass || options.prefetchedClass } : {},
```
Comment (pi0) [inline packages/nuxt/src/app/components/nuxt-link.ts:229]:
```suggestion
              ...((prefetched.value && !props.custom) ? { class: props.prefetchedClass || options.prefetchedClass } : {}),
```

**Review by pi0 — APPROVED** [review]
