### PR TITLE
fix(kit): use `pathe` to resolve aliases

### LINKED ISSUE #7008: [kit] resolveAlias should sort keys by length first
### Environment

It doesn't matters, but 

- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0-rc.8`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `alias`, `components`, `css`, `srcDir`, `dir`, `telemetry`, `modern`, `modules`, `vite`, `nitro`, `autoImports`, `typescript`

### Reproduction

-

### Describe the bug

[Source of `resolveAlias` function](https://github.com/nuxt/framework/blob/25ef26c38d4b358a9e7b09a7bac4b972fe2269c9/packages/kit/src/resolve.ts#L104)

```
import { resolveAlias } from '@nuxt/kit';

const aliases = {
  "~": "root/",
  "~components": "root/some/deep/nested/components/"
};

console.log(resolveAlias("~components/something.vue", aliases));
```

It outputs:  `root/components/something.vue`
Expected output - `root/some/deep/nested/components/something.vue`

### Additional context

I can make a PR after confirming that this isn't done intentionally

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #7008

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We have some upstream fixes in `pathe/utils` that we can take advantage of in kit.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/kit/src/resolve.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { promises as fsp, existsSync } from 'node:fs'
 import { fileURLToPath } from 'node:url'
 import { basename, dirname, resolve, join, normalize, isAbsolute } from 'pathe'
 import { globby } from 'globby'
-import { normalizeAliases } from 'pathe/utils'
+import { normalizeAliases, resolveAlias as _resolveAlias } from 'pathe/utils'
```
Comment (danielroe) [inline packages/kit/src/resolve.ts:5]:
```suggestion
import { resolveAlias as _resolveAlias } from 'pathe/utils'
```

**Review by Atinux — APPROVED** [review]

File: packages/kit/src/resolve.ts [hunk 2]
```diff
@@ -106,13 +106,7 @@ export function resolveAlias (path: string, alias?: Record<string, string>): str
   if (!alias) {
     alias = tryUseNuxt()?.options.alias || {}
   }
-  for (const key in normalizeAliases(alias)) {
-    if (key === '@' && !path.startsWith('@/')) { continue } // Don't resolve @foo/bar
```
Comment (pi0) [inline packages/kit/src/resolve.ts:110]: Note that we have removed @ and @/ check from pathe util

Comment (danielroe) [reply packages/kit/src/resolve.ts:110]: But we now respect path separate which should do the same thing.
