### PR TITLE
fix(schema): add typings for `vite.vue` options

### LINKED ISSUE #6218: Missing types for `vite.vue`
### Reproduction

https://stackblitz.com/edit/github-wnp6ht?file=nuxt.config.ts

### Describe the bug

We provide an extended `vite.vue` options to configure the Vue plugin, and it's defined in the schema: https://github.com/nuxt/framework/blob/943dc0e16ebc046378dbe09e7fe9771fac85bf9c/packages/schema/src/config/vite.ts#L34-L41

However, `untyped` does not seem to generate the extension of the types but has been overridden by `UserConfig`. Similar situation occurred in #6217 as `vite.viteNode`.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #6218

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds typings for `vite.vue` to the schema.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Atinux — APPROVED** [review]

**Comment by antfu** [comment]
I have tried to do this, but it seems `ViteConfig` does not been copied over to the generated .d.ts

```ts
export interface ViteConfig extends UserConfig {
  /**
   * Options passed to @vitejs/plugin-vue
   * @see https://github.com/vitejs/vite/tree/main/packages/plugin-vue
   */
  vue?: VuePluginOptions
  /**
   * Bundler for dev time server-side rendering.
   * @default 'vite-node'
   */
  serverBundler?: 'vite-node' | 'legacy'
}

export default {
  /**
   * Configuration that will be passed directly to Vite.
   *
   * See https://vitejs.dev/config for more information.
   * Please note that not all vite options are supported in Nuxt.
   *
   * @type {ViteConfig}
   * @version 3
   */
```

**Comment by danielroe** [comment]
You can currently use `@typedef` inline within that file, or use a pattern like this: https://github.com/nuxt/framework/blob/12ebe3aeb6458056a1db9c77ce26e446b3af368a/packages/schema/src/config/_app.ts#L103

**Review by antfu — APPROVED** [review]

File: packages/schema/src/types/config.ts [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import { ConfigSchema } from '../../schema/config'
 import type { ResolvedConfig } from 'c12'
+import { UserConfig } from 'vite'
```
Comment (pi0) [inline packages/schema/src/types/config.ts:3]: We could rename this import with `vite` in it and use `import type`
