### PR TITLE
fix(nuxt): relax server import protections

### LINKED ISSUE #5354: allow importing from generic `~/server/utils`
Generally, it would happen to developers using unwanted imports with shared utils but I guess we can limit this to a convention and remove import protection for unknown folders like /utils to be usable also for server files 👍🏼

https://github.com/nuxt/framework/discussions/3282#discussioncomment-2859451

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5354

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This removes import protection outside of `~/server/api/` and `~/server/middleware/` directories, for shared utilities.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/core/plugins/import-protection.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@ export const vueAppPatterns = (nuxt: Nuxt) => [
     [new RegExp(`^${escapeRE(m)}$`), 'Importing directly from module entry points is not allowed.']),
   ...[/(^|node_modules\/)@nuxt\/kit/, /^nitropack/]
     .map(i => [i, 'This module cannot be imported in the Vue part of your app.']),
-  [new RegExp(escapeRE(resolve(nuxt.options.srcDir, (nuxt.options.dir as any).server || 'server'))), 'Importing from server middleware is not allowed in the Vue part of your app.']
+  [new RegExp(escapeRE(resolve(nuxt.options.srcDir, (nuxt.options.dir as any).server || 'server')) + '\\/(api|middleware)\\/'), 'Importing from server middleware is not allowed in the Vue part of your app.']
```
Comment (pi0) [inline packages/nuxt/src/core/plugins/import-protection.ts:23]:
```suggestion
  [new RegExp(escapeRE(resolve(nuxt.options.srcDir, (nuxt.options.dir as any).server || 'server')) + '\\/(api|middleware|plugins)\\/'), 'Importing from server is not allowed in the Vue part of your app.']
```

File: packages/nuxt/src/core/plugins/import-protection.ts [hunk 2]
```diff
@@ -20,7 +20,7 @@ export const vueAppPatterns = (nuxt: Nuxt) => [
     [new RegExp(`^${escapeRE(m)}$`), 'Importing directly from module entry points is not allowed.']),
   ...[/(^|node_modules\/)@nuxt\/kit/, /^nitropack/]
     .map(i => [i, 'This module cannot be imported in the Vue part of your app.']),
-  [new RegExp(escapeRE(resolve(nuxt.options.srcDir, (nuxt.options.dir as any).server || 'server'))), 'Importing from server middleware is not allowed in the Vue part of your app.']
+  [new RegExp(escapeRE(resolve(nuxt.options.srcDir, (nuxt.options.dir as any).server || 'server')) + '\\/(api|middleware|plugins)\\/'), 'Importing from server is not allowed in the Vue part of your app.']
```
Comment (pi0) [inline packages/nuxt/src/core/plugins/import-protection.ts:23]:
```suggestion
  [new RegExp(escapeRE(resolve(nuxt.options.srcDir, (nuxt.options.dir as any).server || 'server')) + '\\/(api|routes|middleware|plugins)\\/'), 'Importing from server is not allowed in the Vue part of your app.']
```
