### PR TITLE
fix(vite): improve `vite-node` hmr

### LINKED ISSUE #6243: `vite-node` server HMR is broken
### Environment

- Operating System: `Linux`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.6-27651720.5dc864d`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `experimental`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

(on Windows, Linux, Docker (Linux) or WSL2 environment)

- Create new project with `npx nuxi init` (swit
- Enable vite-node with `experimental
- Run dev server with `npm run dev`
- Write simple `app.vue` such as `<template><div>Hello world!</div></template>`
- Open http://localhost:3000
- Edit `app.vue` 
- Reload

### Describe the bug

Client is updated with HMR and subsequent reloads but server is not. Causing hydration error.

It might be related to the issue https://github.com/nuxt/framework/issues/2047 since now client HMR on Linux works and Server not (in current nuxt, it is otherwise). But also trying CHOKIDAR_USEPOLLING=1 I still have same issues.

image

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

close #6243

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR implemented the full HMR support of vite-node as mentioned in https://github.com/nuxt/framework/pull/6154#issuecomment-1195505167

Re #6243, the bug is caused because in the release build, `entry.mjs` is laying under `node_modules` which bypasses the cache clear up due to https://github.com/nuxt/framework/pull/6153

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/vite/src/runtime/vite-node.mjs [hunk 1]
```diff
@@ -20,13 +20,17 @@ export default async (ssrContext) => {
...
+
+  // Invaildate cache for files changed since last rendering
+  const invalidates = await $fetch('/invalidates', {
+    baseURL: viteNodeOptions.baseURL
+  })
+  for (const key of invalidates) {
+    runner.moduleCache.delete(key)
+  }
+
+  // Execute SSR bundle on-demand
```
Comment (DamianGlowala) [inline packages/vite/src/runtime/vite-node.mjs:32]:
```suggestion
  // Execute SSR bundle on demand
```

File: packages/vite/src/vite-node.ts [hunk 2]
```diff
@@ -49,14 +65,28 @@ function getManifest (server: ViteDevServer) {
...
+function createViteNodeMiddleware (ctx: ViteBuildContext, invalidateIDs: Set<string> = new Set()) {
   const app = createApp()
 
   app.use('/manifest', defineEventHandler(() => {
     const manifest = getManifest(ctx.ssrServer)
     return manifest
   }))
 
+  app.use('/invalidates', defineEventHandler(() => {
+    // When a file has been invalidate, we also invalidate the entry module
```
Comment (DamianGlowala) [inline packages/vite/src/vite-node.ts:78]:
```suggestion
    // When a file has been invalidated, we also invalidate the entry module
```

**Review by DamianGlowala — CHANGES_REQUESTED** [review]

**Comment by pi0** [comment]
This is nice solution <3 

Locally trying on an external project (MacOS), Server HMR seems perfectly working but only we are invalidating some unnecessary chunks. Which could be probably improved later.

image

**Review by pi0 — APPROVED** [review]
