### PR TITLE
fix(schema): type `render.compressor`

### LINKED ISSUE #2286: fix: compressor typing
### Environment

- Nuxt Version:     `2.16.0-27311057.ab1c6cb4`
- Nuxt Schema Version: `3.0.0-27307420.6a25d3e`

### Reproduction

Use `import shrinkRay from 'shrink-ray-current'` and set nuxt.config's `render.compressor` option to `shrinkRay()`.

### Describe the bug

There is the following Typescript error:
`Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' is not assignable to type '{ threshold: number; } | { threshold?: number | undefined; } | undefined'.
  Type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>' has no properties in common with type '{ threshold?: number | undefined; }'.ts(2322)`
The [compressor field](https://github.com/nuxt/framework/blob/d68318f9d5ee25f6377edb866cd1b5846e8bfdce/packages/schema/src/config/render.ts#L104) currently only allows `threshold: number`, but its comments says `Set to ``false`` to disable compression. You can also pass an object of options for [compression middleware](https://www.npmjs.com/package/compression), or use your own middleware by passing it in directly - for example, ``otherComp({ myOptions: 'example' })``.`

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #2286

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Adds type for `render.compressor` (only relevant for Bridge).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/config/render.ts [hunk 1]
```diff
@@ -99,6 +99,8 @@ export default {
    * for [compression middleware](https://www.npmjs.com/package/compression), or
    * use your own middleware by passing it in directly - for example,
    * `otherComp({ myOptions: 'example' })`.
+   *
+   * @type {boolean | typeof import('compression').CompressionOptions | ((req: typeof import('http').IncomingMessage, res: typeof import('http').ServerResponse, next: (err?: any) => void) => any) }
```
Comment (pi0) [inline packages/schema/src/config/render.ts:103]: This schema is targetting Bridge (which uses Nitro) and Nuxt3. Maybe only typing `compression` options (as an object) is enough?
