### PR TITLE
fix(kit): use closest nuxt package for `loadNuxt`

### LINKED ISSUE #1685: kit and nuxi picks `nuxt 3` in monorepo over `nuxt 2`
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.18.1`
- Nuxt Version:     `2.15.8`
- Package Manager:  `yarn@3.1.0`
- Bundler:          `Webpack`
- User Config:      `components`, `serverMiddleware`, `buildDir`, `plugins`, `nitro`, `bridge`, `vite`, `buildModules`
- Runtime Modules:  `-`
- Build Modules:    `@nuxt/bridge@3.0.0`
------------------------------

### Describe the bug

If two versions of nuxt are installed, [`loadNuxt` util](https://github.com/nuxt/framework/blob/bd7e3b41de9c137ed56aaedc9e0f92e6eaa547ee/packages/kit/src/nuxt.ts#L29) tries to resolve(up) for `nuxt3` and assume using nuxt 3 while in a monorepo with two versions installed, it should prefer the closest version in `node_modules`

### Reproduction

https://github.com/nuxt/framework/tree/bd7e3b41de9c137ed56aaedc9e0f92e6eaa547ee/test/fixtures/bridge

Use `yarn dev`

### Additional context

Version inference is also wrong

### Logs

```shell
ERROR  Cannot start nuxt:  postcss@8 is not compatible with current version of nuxt (0.0.0). Expected: >=2.15.3                                                                                                                                                                      09:31:29

  at Object.postcss8Module (/home/pooya/Code/framework/packages/bridge/node_modules/@nuxt/postcss8/dist/index.js:19:11)
  at installModule (/home/pooya/Code/framework/packages/kit/src/module/install.ts:63:17)
  at setup (/home/pooya/Code/framework/packages/bridge/src/module.ts:58:36)
  at async installModule (/home/pooya/Code/framework/packages/kit/src/module/install.ts:63:3)
  at async initNuxt (/home/pooya/Code/framework/packages/nuxt3/src/core/nuxt.ts:62:5)
  at async load (/home/pooya/Code/framework/packages/nuxi/src/commands/dev.ts:55:9)
  at async Object.invoke (/home/pooya/Code/framework/packages/nuxi/src/commands/dev.ts:98:5)
  at async _main (/home/pooya/Code/framework/packages/nuxi/src/index.ts:40:7)
```

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

resolves #1685

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/kit/src/nuxt.ts [hunk 1]
```diff
@@ -21,21 +22,24 @@ export interface LoadNuxtOptions extends LoadNuxtConfigOptions {
...
   const resolveOpts: RequireModuleOptions = { paths: opts.rootDir }
 
-  // Detect version
-  if (!opts.version) {
-    opts.version = tryResolveModule('nuxt3', resolveOpts) ? 3 : 2
+  const nearestNuxtPkg = await Promise.all(['nuxt3', 'nuxt-edge', 'nuxt']
+    .map(pkg => resolvePackageJSON(pkg, { url: opts.rootDir }).catch(() => null)))
+    .then(r => r.filter(Boolean).sort((a, b) => b.length - a.length)[0])
+  if (!nearestNuxtPkg) {
+    throw new Error(`Cannot find any nuxt version from ${opts.rootDir}`)
```
Comment (danielroe) [inline packages/kit/src/nuxt.ts:36]: Perhaps if we don't find a `package.json` we just fall back to `tryResolveModule` instead?

Comment (pi0) [reply packages/kit/src/nuxt.ts:36]: If package.json of neither nuxt/nuxt-edge/nuxt3 is not found how `tryResolveModule` is expected to find it?
