### PR TITLE
fix(nuxi): always override `NODE_ENV`

### LINKED ISSUE #5196: NODE_ENV overwriting results in weird errors
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `yarn@3.1.1`
- Builder:          `vite`
- User Config:      `ssr`, `runtimeConfig`, `typescript`, `css`, `buildModules`, `intlify`, `alias`
- Runtime Modules:  `-`
- Build Modules:    `@vueuse/nuxt@8.4.2`, `@intlify/nuxt3@0.1.10`
------------------------------

### Reproduction

I stumbled into an issue very similar to the one of https://github.com/nuxt/framework/issues/1913 and https://github.com/nuxt/framework/issues/3730, i.e. overriding `NODE_ENV` environment variable. 
This results in a weird blank page, with no clear info on what happened.

I believe it deserves a warning in the https://v3.nuxtjs.org/guide/features/runtime-config/#environment-variables, it took me a week to figure out that that was the problem.

### Describe the bug

-

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #5196

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds warnings if user is overriding the correct NODE_ENV for build/dev/analyze. (Other commands like preview, typecheck or prepare I felt did not particularly matter, but happy to expand the warnings.)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxi/src/commands/build.ts [hunk 1]
```diff
@@ -13,6 +13,11 @@ export default defineNuxtCommand({
   },
   async invoke (args) {
     process.env.NODE_ENV = process.env.NODE_ENV || 'production'
+
+    if (process.env.NODE_ENV !== 'production') {
+      console.warn(`Building nuxt in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```
Comment (DamianGlowala) [inline packages/nuxi/src/commands/build.ts:18]:
```suggestion
      console.warn(`Building Nuxt in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```

File: packages/nuxi/src/commands/analyze.ts [hunk 2]
```diff
@@ -16,6 +16,10 @@ export default defineNuxtCommand({
   async invoke (args) {
     process.env.NODE_ENV = process.env.NODE_ENV || 'production'
 
+    if (process.env.NODE_ENV !== 'production') {
+      console.warn(`Building nuxt for analysis in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```
Comment (DamianGlowala) [inline packages/nuxi/src/commands/analyze.ts:20]:
```suggestion
      console.warn(`Building Nuxt for analysis in \`${process.env.NODE_ENV}\` mode. This is not recommended.`)
```

**Review by DamianGlowala — CHANGES_REQUESTED** [review]

**Comment by pi0** [comment]
Thanks for the PR but if we are not recommending custom NODE_ENV, there is no reason to allow overriding it I think. However, it is also worth tracking down what happens with custom env specially for non development builds. It can be simply one or two bugs.

**Comment by danielroe** [comment]
The cause of https://github.com/nuxt/framework/issues/5196 is really a Vite bug (or perhaps it's unfair to say that it's a bug - we could say that Vite does not support _building_ in development mode). Here's how it happens:

1. `options.dev` is set to true if `NODE_ENV` is overridden
2. vitejs/plugin-vue injects HMR code because it's not production: https://github.com/vitejs/vite/blob/main/packages/plugin-vue/src/main.ts#L131-L139
3. vite replaces `import.meta.hot` with `false` because we're building: https://github.dev/vitejs/vite/blob/main/packages/vite/src/node/plugins/define.ts#L32-L45

I would be very happy with _not_ allowing `NODE_ENV` to be overridden, but think if we do then we should definitely warn. What was the reason you originally added it (https://github.com/nuxt/framework/commit/586709a82d7ce45d7cbd528bb7ee002dccae5611)?

**Comment by pi0** [comment]
Thanks for explaining! I think we can then change the strategy to override to what we expect but also warn if user already set a `NODE_ENV` we are overriding and saying hay, we just ignored your env ?

File: packages/nuxi/src/commands/analyze.ts [hunk 3]
```diff
@@ -14,7 +14,11 @@ export default defineNuxtCommand({
     description: 'Build nuxt and analyze production bundle (experimental)'
   },
   async invoke (args) {
-    process.env.NODE_ENV = process.env.NODE_ENV || 'production'
+    if (process.env.NODE_ENV && process.env.NODE_ENV !== 'production') {
+      console.info('Setting NODE_ENV to `production`.')
```
Comment (pi0) [inline packages/nuxi/src/commands/analyze.ts:18]: Can we please use a warning and also show the user-provided value that is being ignored?

Comment (pi0) [reply packages/nuxi/src/commands/analyze.ts:18]: (this can be refactored to a common utility too I guess now)

File: packages/nuxi/src/utils/env.ts [hunk 4]
```diff
@@ -0,0 +1,8 @@
+export const overrideEnv = (targetEnv: string) => {
+  const currentEnv = process.env.NODE_ENV
+  if (currentEnv && currentEnv !== targetEnv) {
+    console.warn(`Changing NODE_ENV from \`${currentEnv}\` to \`${targetEnv}\`.`)
```
Comment (pi0) [inline packages/nuxi/src/utils/env.ts:4]:
```suggestion
    console.warn(`Changing \`NODE_ENV\` from \`${currentEnv}\` to \`${targetEnv}\`.`)
```

**Review by pi0 — APPROVED** [review]
