### PR TITLE
fix(nuxt3): initialise router with normalised url

### LINKED ISSUE #4417: Server-side rendering (SSR) of a custom Nuxt error page leads to Vue Router warning: No match found for location with path "/__nuxt_error?..."
### Environment

```
Nuxt CLI v3.0.0-27501460.04a72f8
RootDir: /home/projects/github-hf1mjb
Nuxt project info:

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-27501460.04a72f8`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

### Reproduction

https://stackblitz.com/edit/github-hf1mjb?file=pages/index.vue

### Describe the bug

Hello.

I get a Vue Router warning in the Terminal when a custom Nuxt error page is used:

```
[Vue Router warn]: No match found for location with path "/__nuxt_error?url=/test/404&statusCode=404&statusMessage=Route+Not+Found&message=+&description"
```

Best wishes,
Sergey.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #4417

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

`ssrContext.req.url` displays the full error handler URL rather than the cleaned-up version. This PR changes it to use the path that the error handler is invoked for.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/pages/runtime/router.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ export default defineNuxtPlugin((nuxtApp) => {
   }
 
   // Allows suspending the route object until page navigation completes
-  const path = process.server ? nuxtApp.ssrContext.req.url : createCurrentLocation(baseURL, window.location)
+  const path = process.server ? nuxtApp.ssrContext.url : createCurrentLocation(baseURL, window.location)
```
Comment (pi0) [inline packages/nuxt3/src/pages/runtime/router.ts:85]: This is a good fix per se but also worries me that error URL could be properly encoded that this doesn't happens with URL mismatch.

Comment (danielroe) [reply packages/nuxt3/src/pages/runtime/router.ts:85]: Do you have an example of what that might look like? We are using `withQuery` and `useQuery` which (if I understand rightly) _should_ make this an upstream issue to add tests for in `ufo`.

Comment (pi0) [reply packages/nuxt3/src/pages/runtime/router.ts:85]: > should make this an upstream issue to add tests for in ufo.

ufo utils don't update formating and are based on non-encoded by default. This is kinda normal behavior.

> Do you have an example of what that might look like

URL we are generating for `/_error/*` fetch call can be encoded.
