### PR TITLE
fix(schema): cleanup meta tags and deduplicate charset/viewport

### LINKED ISSUE #4394: nuxt3 meta tag error
### Environment

node 16.2
npm 8.5.0

### Reproduction
https://v3.nuxtjs.org/guide/directory-structure/nuxt.config
https://v3.nuxtjs.org/guide/features/head-management
I followed the guide in the documentation.

### Describe the bug

nuxt3 meta tag error

1. nuxt.config.ts
`{ charset: 'utf-8' },`
output - html
```html
<meta charset="utf-8">
<meta charset="utf-8">
```
Two appear as duplicates.

2. nuxt.config.ts
` { name: 'title', content: 'asd' },`
output - html
```html
<meta hid:'title' name: 'title', content: 'asd' >
```

In html, hid is also output. can i get rid of this?
Also, does the hid phrase affect seo?

And when meta tags are entered together in nuxt.config.ts and individual pages, both appear. It appears as a duplicate, and even if both are aliased with hid, 2 are output as duplicates.

3. nuxt.config.ts
4. 
` { hid:'canonical', rel: 'canonical', href: 'https://domain/' }`

index.vue
```js
 useHead({
            link: [
                { hid:'canonical', rel: 'canonical', href: 'https://domain/' }
            ],
        })
    }
```
Catalina also shows 2 duplicate tags in html.

nuxt.confug.ts common option add
```
    ssr : false,
    target: 'server',
```
help.

Lastly, after build, not only meta tag, but also sitemap should be provided to optimize for reflection in seo?

It seems that the tags do not recognize the SEO optimization on the Naver site.
https://www.naver.com/
eqqeggeqgeqgqegeqgqe

qqgeqgeeqgeqg

### Additional context

_No response_

### Logs

_No response_

### LINKED ISSUE #6317: Cannot read properties of null (reading 'getAttribute') infinite log loop
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.16.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `telemetry`, `postcss`, `css`, `runtimeConfig`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

For any project, even a starter, set the config to the following
```typescript
// nuxt.config.ts
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  meta: {
    script: [undefined],
  },
});
```

### Describe the bug

- When running locally, the error messages are logged infinitely until you stop the dev server. And the page never loads.
- When deploying to cloudflare, you get the "Exceeded resources limit" error page when navigating to the site.

This bug occurs with most RC versions but I did not check most before RC-3

### Additional context

I got to this issue because I had a configuration that looks something like this for the standalone Vuejs devtools
```typescript
import { defineNuxtConfig } from 'nuxt';

export default defineNuxtConfig({
  meta: {
    script: [
      process.env.NODE_ENV === 'development'
      ? { src: `http://localhost:8098` }
      : undefined,
    ],
  },
});
```

Which made it difficult to spot during development, and resolving it meant replacing `undefined` with an empty object `{}`

### Logs

```shell
[h3] [unhandled] H3Error$1: Cannot read properties of null (reading 'getAttribute')
    at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Cannot read properties of null (reading 'getAttribute')
  at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
[Vue warn]: Component <Anonymous> is missing template or render function.
[h3] [unhandled] H3Error$1: Cannot read properties of null (reading 'getAttribute')
    at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Cannot read properties of null (reading 'getAttribute')
  at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
[Vue warn]: Component <Anonymous> is missing template or render function.
[h3] [unhandled] H3Error$1: Cannot read properties of null (reading 'getAttribute')
    at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Cannot read properties of null (reading 'getAttribute')
  at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
[Vue warn]: Component <Anonymous> is missing template or render function.
[h3] [unhandled] H3Error$1: Cannot read properties of null (reading 'getAttribute')
    at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
    at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
    at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
    at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
    at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
[nuxt] [request error] Cannot read properties of null (reading 'getAttribute')
  at createError (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:191:15)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:381:21)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at r (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
  at response (C:\Users\bsgum\dev\gits-web\node_modules\unenv\runtime\fetch\index.mjs:9:13)
  at html (C:\Users\bsgum\dev\gits-web\node_modules\ohmyfetch\dist\chunks\fetch.mjs:131:9)
  at Object.onError (C:\Users\bsgum\dev\gits-web\node_modules\nuxt\dist\core\runtime\nitro\error.mjs:24:9)
  at nodeHandler (C:\Users\bsgum\dev\gits-web\node_modules\h3\dist\index.mjs:388:19)
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #6317, resolves #4394

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This sanitises user input for meta config, including preventing duplicate viewport + charsets (via meta and also top-level setting). It also removes a bit of code that was previously added for Bridge support, which didn't have access to schema.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/schema/src/config/_app.ts [hunk 1]
```diff
@@ -105,15 +105,21 @@ export default {
      */
     head: {
       $resolve: (val, get) => {
-        return defu(val, get('meta'), {
-          charset: 'utf-8',
-          viewport: 'width=device-width, initial-scale=1',
+        const resolved = defu(val, get('meta'), {
+          charset: val?.meta?.find(m => m.charset)?.charset ?? 'utf-8',
+          viewport: val?.meta?.find(m => m.name === 'viewport')?.content ?? 'width=device-width, initial-scale=1',
```
Comment (pi0) [inline packages/schema/src/config/_app.ts:110]: This logic could be simpler if we resolver after applying defu to conditionally set default viewport/charset.

File: test/fixtures/basic/nuxt.config.ts [hunk 2]
```diff
@@ -2,6 +2,13 @@ import { defineNuxtConfig } from 'nuxt'
 import { addComponent } from '@nuxt/kit'
 
 export default defineNuxtConfig({
+  app: {
+    head: {
+      charset: 'utf-8',
+      link: [undefined],
+      meta: [{ name: 'viewport', content: 'width=1024, initial-scale=1' }, { charset: 'utf-8' }]
```
Comment (pi0) [inline test/fixtures/basic/nuxt.config.ts:9]: Does it makes sense to disallow `{ name: 'veiewport }` and `{ charset }` from typescript when we have top level `head` version for them? This way we can have one single source of trust for them after schema normalization

File: packages/schema/src/config/_app.ts (hunk 1 above)
Comment (danielroe) [reply packages/schema/src/config/_app.ts:110]: I guess I want to distinguish between which is source of truth. So if `head.charset` is resolved to `utf-8` - was that because user set it or because that was the default value?

File: test/fixtures/basic/nuxt.config.ts (hunk 2 above)
Comment (danielroe) [reply test/fixtures/basic/nuxt.config.ts:9]: Nice idea. Currently they are entirely untyped though. It will be a good enhancement to port across the good TS work from https://github.com/nuxt/framework/pull/6251, but probably a subsequent PR? Will create issue.

File: packages/schema/src/config/_app.ts (hunk 1 above)
Comment (pi0) [reply packages/schema/src/config/_app.ts:110]: Hmmm, we can add 3rd arg to defu too. Not sure which syntax is more readable

**Review by pi0 — APPROVED** [review]
