### PR TITLE
fix(nuxt): improve hmr for pages macros

### LINKED ISSUE #8820: HMR doesn't work for pages (3.0.0-rc.13)
### Environment

- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@7.17.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-mwpzkm?file=app.vue,pages%2Findex.vue

### Describe the bug

Any change made to files in `pages` directory causes to page reload.

But changes made to app.vue (for example) are applied through HMR correctly.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by antfu**
### 🔗 Linked issue

close #8820

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt/src/pages/page-meta.ts [hunk 1]
```diff
@@ -13,6 +13,18 @@ export interface PageMetaPluginOptions {
...
+const __nuxt_page_meta = {}
+export default __nuxt_page_meta
+`
+
+const CODE_HMR = `
+if (import.meta.hot) {
+  import.meta.hot.accept(mod => {
+    Object.assign(__nuxt_page_meta, mod)
+  })
+}`
```
Comment (danielroe) [inline packages/nuxt/src/pages/page-meta.ts:26]: shall we also add webpack hmr code and wrap the whole thing in `if (process.dev)`?

https://github.com/nuxt/framework/blob/1700bf822e31ffe2c9ec66b61d6f6562d45dcf2b/packages/nuxt/src/app/config.ts#L72-L77

**Review by danielroe — COMMENTED** [review]
thank you so much for looking at this ❤️

**Review by pi0 — APPROVED** [review]
