### PR TITLE
fix(nitro): treat bootrap dep as an entry file

### LINKED ISSUE #2553: renderStyles does not render styles for app.vue dependencies
### Environment

```
$ npx nuxi info
npx: installed 2 in 2.623s
Nuxt CLI v3.0.0-27338323.1e98259                                                                                                                                                                                                20:33:25
RootDir: /srv/app                                                                                                                                                                                                        20:33:25
Nuxt project info:                                                                                                                                                                                                              20:33:25

------------------------------
- Operating System: `Linux`
- Node Version:     `v14.17.6`
- Nuxt Version:     `latest`
- Package Manager:  `unknown`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt.js/issues/new                                                                                                                                                                  20:33:25  

👉 Suggest an improvement: https://github.com/nuxt/nuxt.js/discussions/new

👉 Read documentation: https://nuxtjs.org
```

^ Bundler reports Webpack, but it's actually Vite fyi

Running in Docker node-alpine container

### Reproduction

With some basic test components with scoped styles, run `npx nuxi build`. Nuxt build rolls up the styles into bootstrap CSS file, but nothing seems to load the styles in the browser.

```
export default defineNuxtConfig({
  srcDir: 'context/',
  server: {
    port: process.env.NITRO_PORT
  },
  vite: {
    logLevel: process.env.ENV === 'development' ? 'warn' : 'info',
    server: {
      watch: {
        usePolling: true
      }
    }
  },
  // buildModules: [
  //   '@nuxtjs/pwa'
  // ],
  pwa: {
    manifest: {
      name,
      short_name: name,
      description
    },
    meta: {
      theme_color: theme || undefined,
      name,
      title: name,
      description,
      host
    }
  }
})
```

### Describe the bug

The `bootstrap.{hash}.css` file that the browser runtime loads from `/_nuxt/assets/` reports as having no data, and the rolled up styles never get loaded on the page.

However, A) other assets load fine, and B) hitting the css file URL directly shows the correct output. Also, **dev build is fine**.

Does something need to be configured to tell nuxt to load the styles?

![image](https://user-images.githubusercontent.com/392387/147505606-77daba9b-fbaf-468f-9237-505e07c15934.png)

The following from `.output/server/chunks/app/render.mjs#getSPARenderer` seems to not be getting run:

`renderStyles: () => entryFiles.flatMap(({ css }) => css).filter((css) => css != null).map((file) => `<link rel="stylesheet" href="${publicPath}${file}">`).join(""),`

With manifest data:

```
const client_manifest = {
  "../node_modules/nuxt3/dist/app/entry.mjs": {
    "file": "entry-702f5983.mjs",
    "src": "../node_modules/nuxt3/dist/app/entry.mjs",    
    "isEntry": true,
    "dynamicImports": [
      "../node_modules/nuxt3/dist/app/bootstrap.mjs"      
    ]
  },
  "../node_modules/nuxt3/dist/app/bootstrap.mjs": {       
    "file": "bootstrap-a06256d2.mjs",
    "src": "../node_modules/nuxt3/dist/app/bootstrap.mjs",
    "isDynamicEntry": true,
    "css": [
      "assets/bootstrap.7234385c.css"
    ]
  }
};
```

`curl localhost:8080 | grep stylesheet` on the SSR side also doesn't have any hits.

The output of the log here is empty array:
```
function renderStyles(ssrContext, rendererContext) {
  const { styles } = getRequestDependencies(ssrContext, rendererContext);
        console.log(Object.values(styles))
  return Object.values(styles).map(({ path }) => `<link rel="stylesheet" href="${rendererContext.publicPath}${path}">`).join("");
}
```

and log of getRequestDependencies is: 
```
{
  scripts: {
    '../node_modules/nuxt3/dist/app/entry.mjs': { path: 'entry-702f5983.mjs', type: 'module' }
  },
  styles: {},       <----------------------- WTH????
  preload: {
    '../node_modules/nuxt3/dist/app/entry.mjs': { path: 'entry-702f5983.mjs', type: 'module' }
  },
  prefetch: {
    '../node_modules/nuxt3/dist/app/bootstrap.mjs': { path: 'bootstrap-a06256d2.mjs', type: 'module' },
    'assets/bootstrap.7234385c.css': { path: 'assets/bootstrap.7234385c.css' }
  }
}
```

FYI, there is **NO** `../node_modules` in my container (I wipe them after a build; and there is no `nuxt3` dir in the .output node_modules.)

Going to try without wiping modules and see if that works.

UPDATE: That (^) did not work.

This is looking more like a legit bug: styles are just not rendering.

UPDATE: As a **super** basic nuxt setup, I was using `app.vue`. If using `pages/index.vue`, styles load correctly.

So... **This is either a legit bug that should be fixed, _OR_ app.vue should be documented as totally deprecated (I was under the impression app.vue vs. pages framework was optional)?**


### Additional context

https://github.com/nuxt/framework/blame/main/packages/nitro/src/runtime/app/render.ts
https://github.com/nuxt/framework/commits/main/packages/nitro/src/runtime/app/render.ts

### Logs

_No response_

### LINKED ISSUE #3041: No style loaded when SSR disabled
### Environment

- Node v16.11.1
- Yarn v1.22.5
- Nuxt CLI v3.0.0-27396610.ed4f4f5 

### Reproduction

1. Open app.vue from root dir
2. Add a beautiful : 
```
<style>
body{
	background-color: red !important;
}
</style>
```
3. In nuxt.config.ts set the ssr to false
4. Run yarn build
5. Run yarn start
5. Open localhost:3000

Body stay white unlike body become really red in ssr

### Describe the bug

When we run app in default mode (with ssr), all styles are applied correctly but when you run like described in Reproduction (with no ssr) none style is present.
It's valid case when we use windi, tailwind or whatever else.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #3041, resolves #2553

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When we moved to bootstrap + entry pattern (for module federation support), we inadvertently made the real entrypoint show up in the manifest as a dynamic entrypoint. This fixes that by making all top-level dynamic dependencies of the entrypoint entrypoints too (for SPA renderer).

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nitro/src/runtime/app/render.ts [hunk 1]
```diff
@@ -36,6 +36,7 @@ const getSPARenderer = cachedResult(async () => {
     let entryFiles = Object.values(clientManifest).filter(
       (fileValue: any) => fileValue.isEntry
     )
+    entryFiles.push(...entryFiles.flatMap((e: any) => e.dynamicImports || []).map(i => clientManifest[i]).filter(Boolean))
```
Comment (pi0) [inline packages/nitro/src/runtime/app/render.ts:39]:
```suggestion
    // https://github.com/nuxt/framework/pull/3106
    entryFiles.push(...entryFiles.flatMap((e: any) => e.dynamicImports || []).map(i => clientManifest[i]).filter(Boolean))
```
