### PR TITLE
fix(schema): add back `PublicRuntimeConfig` interface for augmentation

### LINKED ISSUE #4550: Typing of useRuntimeConfig.public
### Environment

- Operating System: `Linux`
- Node Version:     `v16.13.0`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `yarn@1.22.17`
- Builder:          `vite`
- User Config:      `target`, `bridge`, `vite`, `alias`, `nitro`, `ssr`, `meta`, `css`, `tailwindcss`, `modules`, `watch`, `runtimeConfig`, `build`, `storybook`
- Runtime Modules:  `@nuxtjs/tailwindcss@5.0.2`, `@pinia/nuxt@0.1.8`
- Build Modules:    `-`

### Reproduction

https://stackblitz.com/edit/github-ygh9qg?file=test.ts

### Describe the bug

If you provide a custom typescript declaration of the configuration as described in the [docs](https://v3.nuxtjs.org/guide/features/runtime-config#manually-typing-runtime-config),
```ts
declare module '@nuxt/schema' {
  interface RuntimeConfig {
    apiSecret: string
    public: {
      apiBase: string
    }
  }
}
```
then the return value of `useRuntimeConfig()` correctly has an `apiSecret` of type `string` but `pubic` is still `RuntimeConfigNamespace` as declared in `@nuxt/schema/dist/index.d.ts`, and thus has no `apiBase`. The reason is that typescript allows to add new members via type augmentation, but not to overwrite types.

Similarly, with no explicit declaration, nuxt is able to correctly determine the type of the config and put it in `.nuxt/types/schema.d.ts`, but the type of `public` declared there is ignored and `useRuntimeConfig().public` is still the generic `RuntimeConfigNamespace`.

### Additional context

Moreover, one cannot strictly type the return value of `useRuntimeConfig` to only include certain fields. For example, with the above code `useRuntimeConfig().notExisting` is fine, although its not declared in `RuntimeConfig`.
 
### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #4550

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR restores the `PublicRuntimeConfig` interface, as a vehicle for augmenting types for runtimeConfig['public'] which otherwise can't really be done. (Otherwise each augmentation would completely override the type of `public`.)

Particularly value your input @pi0 as you touched this last.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

File: packages/schema/src/types/config.ts [hunk 1]
```diff
@@ -16,15 +16,11 @@ export interface NuxtOptions extends ConfigSchema {
...
 type RuntimeConfigNamespace = Record<string, any>
 
-/** @deprecated use RuntimeConfig interface */
 export interface PublicRuntimeConfig extends RuntimeConfigNamespace { }
 
 /** @deprecated use RuntimeConfig interface */
-export interface PrivateRuntimeConfig extends PublicRuntimeConfig { }
-
-type LegacyRuntimeConfig = PublicRuntimeConfig & Partial<PrivateRuntimeConfig>
+export interface PrivateRuntimeConfig extends RuntimeConfigNamespace { }
```
Comment (pi0) [inline packages/schema/src/types/config.ts:22]: Why would we need this? Having a shortcut to augment `public` namespace makes sense but normally we can augment the rest using `RuntimeConfig`

Comment (danielroe) [reply packages/schema/src/types/config.ts:22]: I think it is only here to avoid a breaking change, but if we're happy to do so, we can remove the legacy type support as well.

Comment (pi0) [reply packages/schema/src/types/config.ts:22]: I'm fine with keeping as deprecated until 3.0.0

**Review by pi0 — APPROVED** [review]
