### PR TITLE
fix(bridge): exclude unsupported imports via `autoImports:sources`

### LINKED ISSUE #4120: export 'BaseTransition' was not found in '/var/app/node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs
### Environment

RootDir: /var/app
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.0`
- Nuxt Version:     `2.16.0-27358576.777a4b7f`
- Package Manager:  `npm@8.3.1`
- Builder:          `webpack`
- User Config:      `rootDir`, `bridge`, `telemetry`, `nitro`, `head`, `publicRuntimeConfig`, `css`, `plugins`, `components`, `buildModules`, `vuetify`, `i18n`, `modules`, `axios`, `compilerOptions`, `build`, `watchers`, `ssr`
- Runtime Modules:  `@nuxtjs/axios@5.13.6`
- Build Modules:    `@nuxtjs/vuetify@1.12.3`, `8n`, `@nuxtjs/dotenv@1.4.1`, `@nuxt/bridge@3.0.0-27485997.c426f3e`
------------------------------

And in my package.json:
```
"scripts": {
    "dev": "nuxi dev --https --port 9004 --host $DOMAIN --ssl-cert $CRT_FILE --ssl-key $KEY_FILE",
}
```

### Reproduction

* Clone this repo: https://github.com/HendrikJan/nuxt-error-demo
* Run 'npx nuxi dev'
* See the errors

### Describe the bug

When running `npm run dev` I get the error:

```
 WARN  Compiled with 67 warnings                          friendly-errors 09:35:32


 WARN  in ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js

"export 'BaseTransition' was not found in '/var/app/node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs'
                                                          friendly-errors 09:35:32

 WARN  in ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js

"export 'EMPTY_ARR' was not found in '/var/app/node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs'

...

 WARN  in ./.nuxt/imports.mjs                             friendly-errors 09:35:32

"export 'clearError' was not found in '#app'              friendly-errors 09:35:32

...

 WARN  in ./node_modules/@nuxt/bridge/dist/runtime/vue2-bridge.mjs

"export 'default' (imported as 'Vue') was not found in 'vue'
```

### Additional context

I'm using Express in serverMiddleware

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #4120

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Imports from presets weren't being passed at `autoImports:extend` as this was only for dynamic imports.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/bridge/src/auto-imports.ts [hunk 1]
```diff
@@ -10,27 +10,25 @@ const CapiHelpers = new Set(Object.keys(CompositionApi))
...
-  nuxt.hook('autoImports:extend', (imports) => {
-    for (const i of imports) {
-      if (i.from === '#app' && UnsupportedImports.has(i.name)) {
-        i.disabled = true
+    const appPreset = presets.find(p => p.from === '#app')
+    if (!appPreset) { return }
+
+    for (const [index, i] of Object.entries(appPreset.imports).reverse()) {
+      if (typeof i === 'string' && UnsupportedImports.has(i)) {
+        appPreset.imports.splice(Number(index), 1)
```
Comment (pi0) [inline packages/bridge/src/auto-imports.ts:27]: Can we disable unsupported instead? And why reversing?

**Review by pi0 — APPROVED** [review]
