### PR TITLE
fix(vite): don't copy `publicDir` files to `_nuxt`

### LINKED ISSUE #1192: Building to .output is placing public files in 2 separate locations
### Environment

```
- Operating System: `Darwin`
- Node Version:     `v16.10.0`
- Nuxt Version:     `3-3.0.0-27238235.a1bcc53`
- Package Manager:  `npm`
- Bundler:          `Webpack`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

### Describe the bug

`npm run build` is placing `public` files in 2 different locations within the `.output` folder. One location is `public` root, and the other location is the `_nuxt` root.

Screen Shot 2021-10-18 at 1 43 50 PM

### Reproduction

Add anything to the `public` folder, run the command `npm run build`, then open the `.output/public` folder to see the duplication.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #1192

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

When building, vite copies `publicDir` contents and places them alongside assets in the `_nuxt` folder. This is an unwanted duplication of assets. (They will never be served from this path.) We can 'fix' this behaviour by simply not copying these files across to `.output/public`.

Ideally we would fix this with a PR to vite itself to allow us to allow js files to be included with `assetsDir` as well, rather than setting vite's `base: '_nuxt'`, which seems like a workaround for our desired nuxt behaviour. (cc: @antfu)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nitro/src/build.ts [hunk 1]
```diff
@@ -30,16 +30,20 @@ async function cleanupDir (dir: string) {
...
+  let publicFiles: string[] = []
   if (await isDirectory(publicDir)) {
+    publicFiles = readDirRecursively(publicDir).map(r => r.replace(publicDir, ''))
     await fse.copy(publicDir, nitroContext.output.publicDir)
   }
 
+  const clientDist = resolve(nitroContext._nuxt.buildDir, 'dist/client')
+  if (await isDirectory(clientDist)) {
+    await fse.copy(clientDist, join(nitroContext.output.publicDir, nitroContext._nuxt.publicPath), {
+      filter: src => !publicFiles.includes(src.replace(clientDist, ''))
```
Comment (pi0) [inline packages/nitro/src/build.ts:43]:
```suggestion
      // TODO: Workaround vite's issue that duplicates public files
      // https://github.com/nuxt/framework/issues/1192
      filter: src => !publicFiles.includes(src.replace(clientDist, ''))
```

**Review by pi0 — APPROVED** [review]
