### PR TITLE
fix(nuxi): ignore static check with `prepare` command

### LINKED ISSUE #1946: Nuxi prepare with target static fails
### Environment

- Operating System: `Windows_NT`
- Node Version:     `v17.0.1`
- Nuxt Version:     `2.16.0-27273615.ab1c6cb4`
- Package Manager:  `yarn@1.22.15`
- Bundler:          `Webpack`
- User Config:      `target`, `bridge`, `vite`, `alias`, `nitro`, `ssr`, `head`, `css`, `plugins`, `components`, `tailwindcss`, `buildModules`, `modules`, `serverMiddleware`, `watch`, `privateRuntimeConfig`, `build`, `storybook`   
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@4.2.1`, `portal-vue/nuxt`, `@nuxt/postcss8@1.1.3`, `@pinia/nuxt@0.1.0`, `nuxt-route-meta@2.3.2`, `@nuxt/bridge@3.0.0-27283410.c53b6a5`

### Reproduction

https://github.com/JabRef/JabRefOnline/pull/480

### Describe the bug

Run `nuxi prepare` with `target: static` yields
```
FATAL  [nitro] Please use nuxt generate for static target                                                                                                                                                                   21:20:28  

  at setupNitroBridge (/D:/Programming/JabRefOnline/node_modules/@nuxt/bridge/dist/chunks/module.mjs:132:11)
  at setup (/D:/Programming/JabRefOnline/node_modules/@nuxt/bridge/dist/chunks/module.mjs:975:13)
  at ModuleContainer.wrappedModule (/D:/Programming/JabRefOnline/node_modules/@nuxt/kit/dist/index.mjs:1212:22)
  at node_modules\@nuxt\bridge\module.cjs:3:58
  at async ModuleContainer.addModule (node_modules\@nuxt\core-edge\dist\core.js:174:20)
  at async ModuleContainer.ready (node_modules\@nuxt\core-edge\dist\core.js:45:7)
  at async Nuxt._init (node_modules\@nuxt\core-edge\dist\core.js:346:5)
```

### Additional context

The error is thrown here
https://github.com/nuxt/framework/blob/850ef69a878294bb2854fdfe07d1d8bc71d0d52d/packages/bridge/src/nitro.ts#L14-L16
I had a look but couldn't find a clear way to specify the information "this is a prepare run" from https://github.com/nuxt/framework/blob/36f3691bf8d3d60b3c5e01ee5df3ed90c6c4780d/packages/nuxi/src/commands/prepare.ts#L18 to the bridge init code.  

### Logs

_No response_

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #1946

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This sets `dev` when running `prepare` to avoid the build-time generate check in the bridge module setup.

I would also consider removing this check entirely.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxi/src/commands/prepare.ts [hunk 1]
```diff
@@ -15,7 +15,7 @@ export default defineNuxtCommand({
     const rootDir = resolve(args._[0] || '.')
 
     const { loadNuxt } = await loadKit(rootDir)
-    const nuxt = await loadNuxt({ rootDir })
+    const nuxt = await loadNuxt({ rootDir, dev: true })
```
Comment (pi0) [inline packages/nuxi/src/commands/prepare.ts:18]: Using dev hides the nuxt 2 static issue but loads nuxt in a wrong state. Modules can be wrong behavior for extending types or even loading unnecessary hooks. Maybe after loading the instance, we can check the condition and check if `nuxt.options.target` is static setting `_legacyGenerate` flag?
