### PR TITLE
fix(nuxt3): use `path` for uniqueness of routes when resolving

### LINKED ISSUE #3892: broken route generation
Hi @kevinmarrec, I created a simple example, try to navigate to /apis, /apps or /dbs. Only the first folder is resolved.
- https://codesandbox.io/s/lively-darkness-cd2x8c

_Originally posted by @wsaca in https://github.com/nuxt/framework/issues/3783#issuecomment-1078653201_

The routes generated are:

```js
export default [
  {
    path: '/apis',
    file: '/sandbox/pages/apis.vue',
    children: [
      {
        name: 'apis',
        path: '',
        file: '/sandbox/pages/apis/index.vue',
        children: [],
        component: () => import('/sandbox/pages/apis/index.vue'),
      },
    ],
    component: () => import('/sandbox/pages/apis.vue'),
  },
  {
    name: 'bd',
    path: '/bd',
    file: '/sandbox/pages/bd/index.vue',
    children: [],
    component: () => import('/sandbox/pages/bd/index.vue'),
  },
  {
    name: 'index',
    path: '/',
    file: '/sandbox/pages/index.vue',
    children: [],
    component: () => import('/sandbox/pages/index.vue'),
  },
]
```

### PR DESCRIPTION
**Pull request by kevinmarrec**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Uniqueness by `name` was a mistake has multiple routes may have `name === undefined` (parents of sub routes).
Routes must be unique by their `path`.

Resolves #3892

### CODE REVIEW

File: packages/nuxt3/src/pages/utils.ts [hunk 1]
```diff
@@ -40,7 +40,7 @@ export async function resolvePagesRoutes (): Promise<NuxtPage[]> {
     })
   )).flat()
 
-  return uniqueBy(allRoutes, 'name')
+  return uniqueBy(allRoutes, 'path')
```
Comment (danielroe) [inline packages/nuxt3/src/pages/utils.ts:43]: thank you! ❤️ 

what do you think about adding a test to ensure we don't regress in future?

Comment (kevinmarrec) [reply packages/nuxt3/src/pages/utils.ts:43]: @danielroe Gotcha

**Comment by kevinmarrec** [comment]
image

image

**Review by pi0 — APPROVED** [review]
