### PR TITLE
fix(nuxt)!: allow `app:rendered` to modify ssr context and add `render:html` 

### LINKED ISSUE #6518: ssrContext effectively read-only in app:rendered hook 3.0.0-rc.7
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.0`
- Nuxt Version:     `3.0.0-rc.7`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-2wanhk?file=plugins/test.client.ts

### Describe the bug

Not sure if this is a bug or if it is intentional. However, in the previous version of the app:rendered hook the ssrContext was mutable.

Using the app:rendered hook you can access the HTML including ssrContext, however, you cannot mutate its value. It seems like the HTML is already generated at this point, and no longer mutable.

`nuxtApp.hook('app:rendered', ({ssrContext}) => {
    ssrContext.payload.state.test = 'test';
  });`

`console.log(window.__NUXT__.state.test) -> undefined`

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by pi0**
### 🔗 Linked issue

Resolves #6518

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

We were calling `app:rendered` hook just after ssr rendering is being done in Nuxt 3 <= 3.0.0-rc.6. #6042 changed this behavior in v3.0.0-rc.7 that `app:rendered` is being called with new `rendered` context to have access to constructed html but this means, it is too late to modify payload. 

This PR reverts `app:rendered` back to previous behavior with new limited `{ ssrContext }` context only. (breaking change)

Nitro plugins have access to the final rendered context via `render:html` (breaking change: `nuxt:app:rendered` renamed for nitro plugins to be simpler, consistent with `render:response` hook and not confused with `app:rendered` lifecycle hook)

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by danielroe — APPROVED** [review]

File: packages/nuxt/src/core/runtime/nitro/renderer.ts [hunk 1]
```diff
@@ -137,42 +135,38 @@ export default defineRenderHandler(async (event) => {
   const renderedMeta = await ssrContext.renderMeta?.() ?? {}
 
   // Create render context
-  const rendered: NuxtRenderContext = {
-    ssrContext,
```
Comment (danielroe) [inline packages/nuxt/src/core/runtime/nitro/renderer.ts:141]: It feels like `ssrContext` would be quite a useful thing to have in this hook. We could mark it in the types as Readonly if that is the main issue.

Comment (pi0) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts:141]: Keeping ssrContext at this point can be source of bad assumptions and possible breaking changes in the future because we already _consumed_ it. I've added `{ event }` in last commit. `event.context` could be used to pass any context from app if needed.

File: test/fixtures/basic/nuxt.d.ts [hunk 2]
```diff
@@ -0,0 +1,8 @@
+// This file is auto generated by `nuxt prepare`
+// Please do not manually modify this file.
+
+/// <reference path=".nuxt-node/nitro.d.ts" />
+/// <reference types="nuxt3" />
+/// <reference path=".nuxt-node/components.d.ts" />
+/// <reference path=".nuxt-node/auto-imports.d.ts" />
+export {}
```
Comment (danielroe) [inline test/fixtures/basic/nuxt.d.ts:8]: this should likely be gitignored.

File: packages/nuxt/src/core/runtime/nitro/renderer.ts (hunk 1 above)
Comment (pi0) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts:141]: Other benefits: At allows garbage collecting ssrContext at this stage by not depending on it and in the future, could be standarized interface in nitro for other integrations depending on html modification.

File: test/fixtures/basic/nuxt.d.ts (hunk 2 above)
Comment (pi0) [reply test/fixtures/basic/nuxt.d.ts:8]: Haha good catch :D

File: packages/nuxt/src/core/runtime/nitro/renderer.ts (hunk 1 above)
Comment (danielroe) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts:141]: I don't think the perf benefit of moving GC up/down a few lines makes much difference. More, that things like payload/state/used components/error information are all accessible on `ssrContext`. Even if the rendering of the Vue app is done, the rendering of the response hasn't yet finished. Users could be forced to awkward workaround of setting ssrContext data on `event` in previous hook in order to consume it in this one.

Marking it as readonly in hook would give a signal to users users that modifying it doesn't have any effect.

Comment (pi0) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts:141]: Rendering of the response is not entirely within vue renderer. And no one should set ssrContext to event context (this is kinda point of not passing it!)

Do you think of any use case right now needs direct access to ssrContext here? (BTW we could always add it to second argument bag `{ event, ssrContext }` if needed)

Comment (matthewhardern) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts:141]: An excellent use case is with web component libraries like lit.dev as it would allow getting the state object to the lit element renderer and then returning the modified HTML as part of the `render:html` hook

Comment (danielroe) [reply packages/nuxt/src/core/runtime/nitro/renderer.ts:141]: That's very helpful, thanks. Would you open a new issue or discussion so we can track, maybe with some example code? I imagine this could get lost in the comments of a merged PR.
