### PR TITLE
fix(nuxt3): respect `srcDir` and normalize string in component dirs

### LINKED ISSUE #3746: Autoimport components dir
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v17.6.0`
- Nuxt Version:     `3.0.0-27458584.91fd16a`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `privateRuntimeConfig`, `app`, `components`, `nitro`, `srcDir`, `build`, `buildModules`, `modern`, `tailwindcss`, `meta`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/tailwindcss@5.0.2`
------------------------------

### Reproduction

--

### Describe the bug

when i trying to start my project with new version of nuxt 3 i have error:
- `[Vue warn]: Failed to resolve component: NavLink
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
Invalid value used as weak map key`

my `nuxt.config.ts`:
```ts
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
	privateRuntimeConfig: {
		secretJWT: process.env.SECRET_JWT,
	},
	app: {
		buildAssetsDir: 'assets/',
	},
	components: {
		global: true,
		dirs: ['~/components'],
	},
	nitro: {
		output: {
			dir: 'build',
		},
		externals: {
			inline: ['uuid'],
		},
	},
	srcDir: 'src',
	build: {
		splitChunks: {
			pages: true,
			layouts: true,
		},
	},
	buildModules: ['@nuxtjs/tailwindcss'],
	modern: true,
	tailwindcss: {
		configPath: '~~/tailwind.config.js',
		viewer: false,
	},
	meta: {
		title: 'Santrek Admin',
		link: [
			{
				rel: 'icon',
				href: '/favicon.svg',
				type: 'image/svg+xml',
			},
		],
	},
});

```

### Additional context

-

### Logs

```shell
-
```

### PR DESCRIPTION
**Pull request by danielroe**
### 🔗 Linked issue

resolves #3746, resolves https://github.com/nuxt/framework/issues/3798

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This fixes two regressions.

1. we handle the possibility of strings in `components.dirs`
2. we resolve `~` to the `srcDir` rather than `cwd` of the layer (is there a reason we're not just using the `alias` config of the layer?)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: packages/nuxt3/src/components/module.ts [hunk 1]
```diff
@@ -24,39 +24,38 @@ export default defineNuxtModule<ComponentsOptions>({
...
       }
-      const dirs = (dir.dirs || [dir]).filter(_dir => _dir.path)
+      const dirs = (dir.dirs || [dir]).map(dir => typeof dir === 'string' ? { path: dir } : dir).filter(_dir => _dir.path)
       return dirs.map(_dir => ({
         ..._dir,
-        path: resolve(cwd, resolveAlias(_dir.path, {
-          ...nuxt.options.alias,
-          '~': cwd
-        }))
+        path: resolveComponentsDir(_dir.path)
```
Comment (pi0) [inline packages/nuxt3/src/components/module.ts:50]: Aliases to srcDir (`~` and `@`) should have the same value across layers. We could keep using `cwd` to allow `path: './components'` possible in layers and `options.srcDir` for resolving aliases, regardless of which layer we are working on. Later, this could be better by introducing named layers (`~theme/components`)

Comment (danielroe) [reply packages/nuxt3/src/components/module.ts:50]: I think you might need to explain the usage a little more then.

You mean `~` should refer to the parent alias? In that case it should either refer to the parent project's _source_ directory, or the layer's _source_ directory - not the `cwd` of the layer. I also think it should have the same value as `@`, and (personally) I think it is more intuitive to resolve it with regard to the _layer's_ source directory, but happy to defer on that as long as it's consistent. 

**Note**: at the moment, the parent directory is broken, even if there are no layers.

Comment (pi0) [reply packages/nuxt3/src/components/module.ts:50]: Can we please only fix top-level isue in this PR and preserve aliases? 

Would be happy to discuss later and explain trade-offs of alias handling for layers.

Comment (danielroe) [reply packages/nuxt3/src/components/module.ts:50]: Very happy to remove `@`, by the way, or make any other changes. I may have missed something that you're aware of, but I think this is a minimal PR that doesn't otherwise change the implementation other than resolving the issues linked.
